---
title: "Reference matrix and pseudobulk creation"
author: "Chris Arian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(23)
```

```{r packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, tibble, tidyr, stringr,readxl, readr, Seurat, SeuratDisk , biomaRt, BiocManager, readr)


#if (!requireNamespace("remotes", quietly = TRUE)) {
  #install.packages("remotes")
#}
#remotes::install_github("mojaveazure/seurat-disk")

```


```{r functions}
#a = object
#b = downsample size
#c = seed set
samp <- function(a, b, c){
  
  ent <- subset(a, cell_type == "Enterocyte")
  gob <- subset(a, cell_type == "Goblet cell")
  other <- subset(a, cell_type == "Other")
  prol <- subset(a, cell_type == "Proliferative cell")
  best4 <- subset(a, cell_type == "BEST4")
  tuft <- subset(a, cell_type == "Tuft cell")
  eec <- subset(a, cell_type == "EEC")
  pan <- subset(a, cell_type == "Paneth cell")
  
  set.seed(c)
  dse <- if(table(Idents(ent)) > b){
            ent[, sample(colnames(ent), size = b, replace = F)]
  } else {
      ent
    }
  set.seed(c)
  dsg <- if(table(Idents(gob)) > b){
            gob[, sample(colnames(gob), size = b, replace = F)]
  } else {
      gob
    }
  set.seed(c)
  dso <- if(table(Idents(other)) > b){
            other[, sample(colnames(other), size = b, replace = F)]
  } else {
      other
    }
  set.seed(c)
  dsp <- if(table(Idents(prol)) > b){
            prol[, sample(colnames(prol), size = b, replace = F)]
  } else {
      prol
    }
  set.seed(c)
  dsb <- if(table(Idents(best4)) > b){
            best4[, sample(colnames(best4), size = b, replace = F)]
  } else {
      best4
    }
  set.seed(c)
  dst <- if(table(Idents(tuft)) > b){
            tuft[, sample(colnames(tuft), size = b, replace = F)]
  } else {
      tuft
    }
  set.seed(c)
  dsee <- if(table(Idents(eec)) > b){
            eec[, sample(colnames(eec), size = b, replace = F)]
  } else {
      eec
    }
  set.seed(c)
  dspan <- if(table(Idents(pan)) > b){
            pan[, sample(colnames(pan), size = b, replace = F)]
  } else {
      pan
    }
  
  merger <- merge(x = dse, y = list(dsg, dso, dsp, dsb, dst, dsee, dspan), merge.data = T)
  return(merger)
}

samp2 <- function(a, b, c, d){
  ct <- subset(a, idents = d)
  set.seed(c)
  subs <- ct[, sample(colnames(ct), size = b, replace = F)]
  return(subs)
}

samp_NOOTHER <- function(a, b, c){
  
  ent <- subset(a, cell_type == "Enterocyte")
  gob <- subset(a, cell_type == "Goblet cell")
  prol <- subset(a, cell_type == "Proliferative cell")
  best4 <- subset(a, cell_type == "BEST4")
  tuft <- subset(a, cell_type == "Tuft cell")
  eec <- subset(a, cell_type == "EEC")
  pan <- subset(a, cell_type == "Paneth cell")
  
  set.seed(c)
  dse <- if(table(Idents(ent)) > b){
            ent[, sample(colnames(ent), size = b, replace = F)]
  } else {
      ent
    }
  set.seed(c)
  dsg <- if(table(Idents(gob)) > b){
            gob[, sample(colnames(gob), size = b, replace = F)]
  } else {
      gob
    }
  set.seed(c)
  dsp <- if(table(Idents(prol)) > b){
            prol[, sample(colnames(prol), size = b, replace = F)]
  } else {
      prol
    }
  set.seed(c)
  dsb <- if(table(Idents(best4)) > b){
            best4[, sample(colnames(best4), size = b, replace = F)]
  } else {
      best4
    }
  set.seed(c)
  dst <- if(table(Idents(tuft)) > b){
            tuft[, sample(colnames(tuft), size = b, replace = F)]
  } else {
      tuft
    }
  set.seed(c)
  dsee <- if(table(Idents(eec)) > b){
            eec[, sample(colnames(eec), size = b, replace = F)]
  } else {
      eec
    }
  set.seed(c)
  dspan <- if(table(Idents(pan)) > b){
            pan[, sample(colnames(pan), size = b, replace = F)]
  } else {
      pan
    }
  
  merger <- merge(x = dse, y = list(dsg, dsp, dsb, dst, dsee, dspan), merge.data = T)
  return(merger)
}


```


```{r paper 1 no imputation pseudobulks}
#load in data
df <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Gut/Paper 1_cell of the human intestinal tract mapped across space and time/paper1_df_nonimputed.rds")


table(Idents(df))

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

```

MAGIC
```{r paper 1 MAGIC pseudobulks}

#load in data
df <- readRDS("~/OneDrive - UW/data for deconv/CPM SEURAT OBJECTS/DS_paper1_cpm.rds")

#load in saver data
#this is a matrix with cells as columns and rows as genes - cell names maintained. I'm going to remake the seurat so that the correct cells are present and add in the daver data from there
magic_df <- read.delim('~/OneDrive - UW/data for deconv/FINAL_df1_MAGIC_matrix.txt',  header = FALSE)
magic_df <- t(magic_df)
colnames(magic_df) <- magic_df[1,]

magic_df <- magic_df[-1,]

magic_cells <- colnames(magic_df)
df <- df[, magic_cells]
df[["MAGIC"]] <- CreateAssayObject(data = magic_df)


## Load in object

#df <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Gut/dataMAGIC/Correct CPM versions/df1_magicobject.rds")

table(Idents(df))

#memory saver
rm(magic_df, magic_cells)


#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp_NOOTHER(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
"Proliferative cell         Enterocyte        Paneth cell 
               793               2892                541 "

#I'll do 1000 cells in each pseudobulk

#1 50% ents

ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$MAGIC$data)
pan <- data.frame(samp2(pseudo, 200, 23, "Paneth cell")@assays$MAGIC$data)


pseudobulk <- cbind(ent, prol, pan) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df1_MAGIC_pb1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 10% ents ## doing 500 cells total
ent <- data.frame(samp2(pseudo, 100, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 700, 23, "Proliferative cell")@assays$MAGIC$data)
pan <- data.frame(samp2(pseudo, 200, 23, "Paneth cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, prol, pan) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df1_MAGIC_pb2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3 25% ents ## 500 cells
ent <- data.frame(samp2(pseudo, 250, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 550, 23, "Proliferative cell")@assays$MAGIC$data)
pan <- data.frame(samp2(pseudo, 200, 23, "Paneth cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, prol, pan) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df1_MAGIC_pb3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 75% ents
ent <- data.frame(samp2(pseudo, 750, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 150, 23, "Proliferative cell")@assays$MAGIC$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$MAGIC$data)


pseudobulk <- cbind(ent, prol, pan) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df1_MAGIC_pb4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5 90% ents
ent <- data.frame(samp2(pseudo, 900, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 50, 23, "Proliferative cell")@assays$MAGIC$data)
pan <- data.frame(samp2(pseudo, 50, 23, "Paneth cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, prol, pan) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df1_MAGIC_pb5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

```

```{r paper 1 MAGIC ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(df_samp@assays$MAGIC$data)
b <- b %>%  mutate_all(function(x) as.numeric((x)))

#b[c(1:10), c(1:10)]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
head(cell_ref)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Signature matrices impute+no impute (D)/Gut/Ref matrices/Paper1_MAGIC_CellRef.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)
```

Paper 2
```{r paper 2 no imputation pseudobulks}
#load in data
df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/chris_df2.rds")

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

```


MAGIC
```{r paper 2 MAGIC pseudobulks}

#load in data
df <- readRDS("/bigdata/faustmanlab/bch/CPM Files/paper2_cpm.rds")

#load in saver data
#this is a matrix with cells as columns and rows as genes - cell names maintained. I'm going to remake the seurat so that the correct cells are present and add in the daver data from there
magic_df <- readr::read_csv("/bigdata/faustmanlab/bch/MAGIC/df2_MAGIC.csv", col_names = TRUE)
magic_df <- t(as.matrix(magic_df))

magic_df <- as.data.frame(magic_df)
colnames(magic_df) <- magic_df[1,]

magic_df <- magic_df[-1,]

magic_cells <- colnames(magic_df)
df <- df[, magic_cells]
df[["MAGIC"]] <- CreateAssayObject(data = as.matrix(magic_df))

df <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Gut/dataMAGIC/Correct CPM versions/df2_magicobject.rds")


table(Idents(df))

#memory saver
rm(magic_df, magic_cells)


#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

### RUN THIS FOR REDOS
pseudo <- readRDS("~/OneDrive - UW/data for deconv/MAGIC_objects_CPM_Correction/pseudo_2_magic.rds")


table(Idents(pseudo))
"Enterocyte       Other Goblet cell   Tuft cell 
       2800        1149         550          42 "
#Lost a lot of cell types - I'll do 1000 cells in each pseudobulk and omit Tuft cells because the count is so low

#1
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$MAGIC$data)
oth <- data.frame(samp2(pseudo, 200, 23, "Other")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 300, 23, "Goblet cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, oth, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, 
            file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df2_MAGIC_pb1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 100, 23, "Enterocyte")@assays$MAGIC$data)
oth <- data.frame(samp2(pseudo, 400, 23, "Other")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 500, 23, "Goblet cell")@assays$MAGIC$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df2_MAGIC_pb2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3
ent <- data.frame(samp2(pseudo, 250, 23, "Enterocyte")@assays$MAGIC$data)
oth <- data.frame(samp2(pseudo, 250, 23, "Other")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 500, 23, "Goblet cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, oth, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df2_MAGIC_pb3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 750, 23, "Enterocyte")@assays$MAGIC$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 150, 23, "Goblet cell")@assays$MAGIC$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df2_MAGIC_pb4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 900, 23, "Enterocyte")@assays$MAGIC$data)
oth <- data.frame(samp2(pseudo, 50, 23, "Other")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 50, 23, "Goblet cell")@assays$MAGIC$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Paper_1/CPM_corrected/df2_MAGIC_pb5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

```

```{r paper 2 MAGIC ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(df_samp@assays$MAGIC$data)
b <- b %>%  mutate_all(function(x) as.numeric((x)))

#b <- expm1(b)
#b[c(1:10), c(1:10)]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
head(cell_ref)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Signature matrices impute+no impute (D)/Gut/Ref matrices/Paper2_MAGIC_CellRef.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)
```



paper 3
```{r paper 3 pseudobulks no imputation}
df <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Gut/Paper 3_epithelial zonation along human small intestine/Paper3_df_CA_Nonimputed.rds")

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident


#sample from data layer 
#This samp() is a function defined earlier
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[,cells_for_pseudo]

```


```{r paper 3 no imputation ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(object = df_samp, layer = "data"))
b <- expm1(b)

#need to rename genes from ensembl to gene names
ens <- rownames(b)
b$GENEID <- rownames(b)

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

b <- left_join(b,ens_to_symbol_biomart, by="GENEID")


#removing any NAs, averaging duplicated genes later below
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
b <- b %>%
      na.omit() %>%
      filter(name != "")%>%
      column_to_rownames(.,"name")%>%
      dplyr::select(.,-GENEID)



#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)


cell_ref <- rbind(t_a, b)


table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Paper3_NoImputation_REFmatrix.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = FALSE)


```


```{r paper 3 SAVER pseudobulks}
#load in data
df <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Gut/Paper 3_epithelial zonation along human small intestine/Paper3_df_CA_Nonimputed.rds")

#load in saver data
#this is a matrix with cells as columns and rows as genes - cell names maintained. I'm going to remake the seurat so that the correct cells are present and add in the daver data from there
saver_df <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Gut/SAVER OUTPUTS/Paper3_SAVERoutput.rds")
saver_cells <- colnames(saver_df)
df <- df[, saver_cells]
df[["SAVER"]] <- CreateAssayObject(data = saver_df)


#memory saver
rm(saver_df, saver_cells)


#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()


table(Idents(pseudo))
"Proliferative cell         Enterocyte        Paneth cell 
               793               2892                541 "

#I'll do 1000 cells in each pseudobulk

#1
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 200, 23, "Goblet cell")@assays$SAVER$data)


pseudobulk <- cbind(ent, prol, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/paper3_SAVER/Paper3_SAVER_pseudobulk_1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 100, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 700, 23, "Proliferative cell")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 200, 23, "Goblet cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/paper3_SAVER/Paper3_SAVER_pseudobulk_2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3
ent <- data.frame(samp2(pseudo, 250, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 550, 23, "Proliferative cell")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 200, 23, "Goblet cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)


#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/paper3_SAVER/Paper3_SAVER_pseudobulk_3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 750, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 150, 23, "Proliferative cell")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/paper3_SAVER/Paper3_SAVER_pseudobulk_4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 900, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 50, 23, "Proliferative cell")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 50, 23, "Goblet cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/paper3_SAVER/Paper3_SAVER_pseudobulk_5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

```

```{r paper 3 SAVER ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(df_samp@assays$SAVER$data)
b <- expm1(b)

#need to rename genes from ensembl to gene names
ens <- rownames(b)
b$GENEID <- rownames(b)

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

b <- left_join(b,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes later below
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
b <- b %>%
      na.omit() %>%
      filter(name != "")%>%
      column_to_rownames(.,"name")%>%
      dplyr::select(.,-GENEID)





#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)


cell_ref <- rbind(t_a, b)


table(colnames(t_a) == colnames(b))
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Signature matrices impute+no impute (D)/Gut/Ref matrices/Paper3_SAVER_REFmatrix.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = FALSE)

```


MAGIC
```{r paper 3 MAGIC pseudobulks}

#load in data
df <- readRDS("/bigdata/faustmanlab/bch/CPM Files/paper3_cpm.rds")

#load in saver data
#this is a matrix with cells as columns and rows as genes - cell names maintained. I'm going to remake the seurat so that the correct cells are present and add in the daver data from there
magic_df <- readr::read_csv("/bigdata/faustmanlab/bch/MAGIC/df3_MAGIC.csv", col_names = TRUE)
magic_df <- t(as.matrix(magic_df))

magic_df <- as.data.frame(magic_df)
colnames(magic_df) <- magic_df[1,]

magic_df <- magic_df[-1,]

magic_cells <- colnames(magic_df)
df <- df[, magic_cells]
df[["MAGIC"]] <- CreateAssayObject(data = as.matrix(magic_df))

df <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Gut/dataMAGIC/Correct CPM versions/df3_magicobject.rds")


table(Idents(df))

#memory saver
rm(magic_df, magic_cells)


#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()



### RUN THIS FOR REDOS
pseudo <- readRDS("~/OneDrive - UW/data for deconv/MAGIC_objects_CPM_Correction/pseudo_3_magic.rds")

table(Idents(pseudo))
# Proliferative cell         Enterocyte        Goblet cell              BEST4 
   #           1565               1860               1006                 16 
#Lost a lot of cell types - I'll do 1000 cells in each pseudobulk and omit BEST4 cells because the count is so low

#I'll do 1000 cells in each pseudobulk

#1
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 200, 23, "Goblet cell")@assays$MAGIC$data)


pseudobulk <- cbind(ent, prol, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Pseudobulks/df3_MAGIC_pb1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 100, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 700, 23, "Proliferative cell")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 200, 23, "Goblet cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Pseudobulks/df3_MAGIC_pb2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3
ent <- data.frame(samp2(pseudo, 250, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 550, 23, "Proliferative cell")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 200, 23, "Goblet cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)



#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Pseudobulks/df3_MAGIC_pb3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 750, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 150, 23, "Proliferative cell")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Pseudobulks/df3_MAGIC_pb4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 900, 23, "Enterocyte")@assays$MAGIC$data)
prol <- data.frame(samp2(pseudo, 50, 23, "Proliferative cell")@assays$MAGIC$data)
gob <- data.frame(samp2(pseudo, 50, 23, "Goblet cell")@assays$MAGIC$data)

pseudobulk <- cbind(ent, prol, gob) %>%
  mutate_all(function(x) as.numeric((x))) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"
pseudobulk$avg <- expm1(pseudobulk$avg)

#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

pseudobulk <- left_join(pseudobulk,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(name) %>%
      summarise(avg = mean(avg)) %>%
      relocate(name) %>%
      filter(name != "")


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Pseudobulks/df3_MAGIC_pb5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

```


```{r paper 3 MAGIC ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(df_samp@assays$MAGIC$data)
b <- b %>%  mutate_all(function(x) as.numeric((x)))

#b <- expm1(b)
#b[c(1:10), c(1:10)]


#need to rename genes from ensembl to gene names
ens <- rownames(b)
b$GENEID <- rownames(b)

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

colnames(ens_to_symbol_biomart) <- c("GENEID", "name")

b <- left_join(b,ens_to_symbol_biomart, by="GENEID")

#removing any NAs, averaging duplicated genes later below
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
b <- b %>%
      na.omit() %>%
      filter(name != "")%>%
      column_to_rownames(.,"name")%>%
      dplyr::select(.,-GENEID)


##

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)


cell_ref <- rbind(t_a, b)


table(colnames(t_a) == colnames(b))
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]
##

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Signature matrices impute+no impute (D)/Gut/Ref matrices/Paper3_MAGIC_CellRef.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = FALSE)
```