---
title: "Reference matrix and pseudobulk creation"
author: "Chris Arian"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, tibble, tidyr, stringr,readxl, ggplot2,ggsci, ggthemes, NormExpression, SoupX, scuttle, Seurat, scran, SeuratDisk, devtools, harmony, biomaRt, BiocManager)


if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")

if (!requireNamespace("org.Hs.eg.db", quietly = TRUE)) BiocManager::install("org.Hs.eg.db")
library(org.Hs.eg.db)

```


```{r functions}
#a = object
#b = downsample size
#c = seed set
samp <- function(a, b, c){
  
  ent <- subset(a, cell_type == "Enterocyte")
  gob <- subset(a, cell_type == "Goblet cell")
  other <- subset(a, cell_type == "Other")
  prol <- subset(a, cell_type == "Proliferative cell")
  best4 <- subset(a, cell_type == "BEST4")
  tuft <- subset(a, cell_type == "Tuft cell")
  eec <- subset(a, cell_type == "EEC")
  pan <- subset(a, cell_type == "Paneth cell")
  
  set.seed(c)
  dse <- if(table(Idents(ent)) > b){
            ent[, sample(colnames(ent), size = b, replace = F)]
  } else {
      ent
    }
  set.seed(c)
  dsg <- if(table(Idents(gob)) > b){
            gob[, sample(colnames(gob), size = b, replace = F)]
  } else {
      gob
    }
  set.seed(c)
  dso <- if(table(Idents(other)) > b){
            other[, sample(colnames(other), size = b, replace = F)]
  } else {
      other
    }
  set.seed(c)
  dsp <- if(table(Idents(prol)) > b){
            prol[, sample(colnames(prol), size = b, replace = F)]
  } else {
      prol
    }
  set.seed(c)
  dsb <- if(table(Idents(best4)) > b){
            best4[, sample(colnames(best4), size = b, replace = F)]
  } else {
      best4
    }
  set.seed(c)
  dst <- if(table(Idents(tuft)) > b){
            tuft[, sample(colnames(tuft), size = b, replace = F)]
  } else {
      tuft
    }
  set.seed(c)
  dsee <- if(table(Idents(eec)) > b){
            eec[, sample(colnames(eec), size = b, replace = F)]
  } else {
      eec
    }
  set.seed(c)
  dspan <- if(table(Idents(pan)) > b){
            pan[, sample(colnames(pan), size = b, replace = F)]
  } else {
      pan
    }
  
  merger <- merge(x = dse, y = list(dsg, dso, dsp, dsb, dst, dsee, dspan), merge.data = T)
  return(merger)
}

samp2 <- function(a, b, c, d){
  ct <- subset(a, idents = d)
  set.seed(c)
  subs <- ct[, sample(colnames(ct), size = b, replace = F)]
  return(subs)
}




```


```{r paper 1 no imputation pseudobulks}
#load in data
df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/paper1_cpm.rds")


table(Idents(df))

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample
df_samp <- samp(df, 300, 23)
table(df$annotation)

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
"Proliferative cell         Enterocyte              BEST4        Paneth cell 
              2953               9286                310               2316 "

#We will be making 5 pseudobulks total with 2000 cells total - refer to code for ground truth values of cell type proportions
#1
ent <- data.frame(samp2(pseudo, 1000, 23, "Enterocyte")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 600, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 300, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 200, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 200, 23, "Enterocyte")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 1300, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 300, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 200, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 1000, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 300, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 200, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 1500, 23, "Enterocyte")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 1800, 23, "Enterocyte")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$RNA$data)


pseudobulk <- cbind(ent, prol, pan) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

```

```{r paper 1 no imputation cell ref CPM}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.matrix(GetAssayData(object = df_samp, layer = "data"))



#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_CellRef_CPM.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```






```{r paper 1 ALRA imputation pseudobulks}

df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/Paper1_df_withALRA.rds")
#need to update cell types
table(Idents(df))

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample
df_samp <- samp(df, 300, 23)

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
"Proliferative cell         Enterocyte              BEST4        Paneth cell 
              2953               9286                310               2316"

#1
ent <- data.frame(samp2(pseudo, 1000, 23, "Enterocyte")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 600, 23, "Proliferative cell")@assays$ALRA$data)
pan <- data.frame(samp2(pseudo, 300, 23, "Paneth cell")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 200, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 200, 23, "Enterocyte")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 1300, 23, "Proliferative cell")@assays$ALRA$data)
pan <- data.frame(samp2(pseudo, 300, 23, "Paneth cell")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 200, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 1000, 23, "Proliferative cell")@assays$ALRA$data)
pan <- data.frame(samp2(pseudo, 300, 23, "Paneth cell")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 200, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 1500, 23, "Enterocyte")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$ALRA$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 1800, 23, "Enterocyte")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$ALRA$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$ALRA$data)


pseudobulk <- cbind(ent, prol, pan) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


```

```{r paper 1 ALRA ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.matrix(df_samp@assays$ALRA$counts)

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)
```


```{r paper 1 SAVER pseudobulks}

#load in data
df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/paper1_cpm.rds")

#load in saver data
#this is a matrix with cells as columns and rows as genes - cell names maintained. I'm going to remake the seurat so that the correct cells are present and add in the daver data from there
saver_df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/Paper1_cpm_SAVERoutput.rds")
saver_df1 <- saver_df[["estimate"]]
saver_cells <- colnames(saver_df1)
df <- df[, saver_cells]
df[["SAVER"]] <- CreateAssayObject(data = saver_df1)


#memory saver
rm(saver_df, saver_cells, saver_df1)
gc()


#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
"Proliferative cell         Enterocyte        Paneth cell 
               820               2889                552 "

#I'll do 1000 cells in each pseudobulk

#1
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$SAVER$data)
pan <- data.frame(samp2(pseudo, 200, 23, "Paneth cell")@assays$SAVER$data)


pseudobulk <- cbind(ent, prol, pan) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 100, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 700, 23, "Proliferative cell")@assays$SAVER$data)
pan <- data.frame(samp2(pseudo, 200, 23, "Paneth cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, pan) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3
ent <- data.frame(samp2(pseudo, 250, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 550, 23, "Proliferative cell")@assays$SAVER$data)
pan <- data.frame(samp2(pseudo, 200, 23, "Paneth cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, pan) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 750, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 150, 23, "Proliferative cell")@assays$SAVER$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, pan) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 900, 23, "Enterocyte")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 50, 23, "Proliferative cell")@assays$SAVER$data)
pan <- data.frame(samp2(pseudo, 50, 23, "Paneth cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, prol, pan) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

```

```{r paper 1 SAVER ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.matrix(df_samp@assays$SAVER$data)

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
head(cell_ref)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)
```



Paper 2
```{r paper 2 no imputation pseudobulks}
#load in data
df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/paper2_cpm.rds")

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
" Enterocyte              Other        Goblet cell          Tuft cell Proliferative cell 
              9050               3998               2312                778                281 
       Paneth cell              BEST4 
               275                153 "


#We will be making 5 pseudobulks total with 2000 cells total - refer to code for ground truth values of cell type proportions
#1
ent <- data.frame(samp2(pseudo, 1000, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 300, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 300, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#2
ent <- data.frame(samp2(pseudo, 200, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 300, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 1100, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#3
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 300, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 800, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#4
ent <- data.frame(samp2(pseudo, 1500, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$RNA$data)
pan <- data.frame(samp2(pseudo, 50, 23, "Paneth cell")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 50, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 1800, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)
```

```{r paper 2 no imputation ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.matrix(GetAssayData(object = df_samp, layer = "data"))

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)
```


```{r paper 2 pseudobulks ALRA}

#load in data
df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/full_df2_withALRA.rds")

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
" Enterocyte              Other        Goblet cell          Tuft cell Proliferative cell 
              9050               3998               2312                778                281 
       Paneth cell              BEST4 
               275                153 "


#We will be making 5 pseudobulks total with 2000 cells total - refer to code for ground truth values of cell type proportions
#I saved the alra imputed data in the "counts" layer of the ALRA assay
#I checked and the counts and data layer of the ALRA assay are identical so it actually doesn't matter for future reference
#1
ent <- data.frame(samp2(pseudo, 1000, 23, "Enterocyte")@assays$ALRA$counts)
oth <- data.frame(samp2(pseudo, 300, 23, "Other")@assays$ALRA$counts)
gob <- data.frame(samp2(pseudo, 300, 23, "Goblet cell")@assays$ALRA$counts)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$counts)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$ALRA$counts)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$ALRA$counts)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$ALRA$counts)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#2
ent <- data.frame(samp2(pseudo, 200, 23, "Enterocyte")@assays$ALRA$counts)
oth <- data.frame(samp2(pseudo, 300, 23, "Other")@assays$ALRA$counts)
gob <- data.frame(samp2(pseudo, 1100, 23, "Goblet cell")@assays$ALRA$counts)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$counts)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$ALRA$counts)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$ALRA$counts)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$ALRA$counts)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#3
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$ALRA$counts)
oth <- data.frame(samp2(pseudo, 300, 23, "Other")@assays$ALRA$counts)
gob <- data.frame(samp2(pseudo, 800, 23, "Goblet cell")@assays$ALRA$counts)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$counts)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$ALRA$counts)
pan <- data.frame(samp2(pseudo, 100, 23, "Paneth cell")@assays$ALRA$counts)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$ALRA$counts)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#4
ent <- data.frame(samp2(pseudo, 1500, 23, "Enterocyte")@assays$ALRA$counts)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$ALRA$counts)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$ALRA$counts)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$counts)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$ALRA$counts)
pan <- data.frame(samp2(pseudo, 50, 23, "Paneth cell")@assays$ALRA$counts)
b4 <- data.frame(samp2(pseudo, 50, 23, "BEST4")@assays$ALRA$counts)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, pan, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 1800, 23, "Enterocyte")@assays$ALRA$counts)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$ALRA$counts)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$ALRA$counts)

pseudobulk <- cbind(ent, oth, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)
```

```{r paper 2 ALRA ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.matrix(df_samp@assays$ALRA$counts)

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
head(cell_ref)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)
```


```{r Paper 2 pseudobulks SAVER}
#load in data
df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/paper2_cpm.rds")

#load in saver data
#this is a matrix with cells as columns and rows as genes - cell names maintained. I'm going to remake the seurat so that the correct cells are present and add in the daver data from there
saver_df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/Paper2_cpm_SAVERoutput.rds")
saver_df1 <- saver_df[["estimate"]]
saver_cells <- colnames(saver_df1)
df <- df[, saver_cells]
df[["SAVER"]] <- CreateAssayObject(data = saver_df1)


#memory saver
rm(saver_df, saver_cells, saver_df1)

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
"Enterocyte       Other Goblet cell   Tuft cell 
       2800        1149         550          42 "
#Lost a lot of cell types - I'll do 1000 cells in each pseudobulk and omit Tuft cells because the count is so low

#1
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$SAVER$data)
oth <- data.frame(samp2(pseudo, 200, 23, "Other")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 300, 23, "Goblet cell")@assays$SAVER$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk1.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 100, 23, "Enterocyte")@assays$SAVER$data)
oth <- data.frame(samp2(pseudo, 400, 23, "Other")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 500, 23, "Goblet cell")@assays$SAVER$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk2.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#3
ent <- data.frame(samp2(pseudo, 250, 23, "Enterocyte")@assays$SAVER$data)
oth <- data.frame(samp2(pseudo, 250, 23, "Other")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 500, 23, "Goblet cell")@assays$SAVER$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk3.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 750, 23, "Enterocyte")@assays$SAVER$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 150, 23, "Goblet cell")@assays$SAVER$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk4.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5
ent <- data.frame(samp2(pseudo, 900, 23, "Enterocyte")@assays$SAVER$data)
oth <- data.frame(samp2(pseudo, 50, 23, "Other")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 50, 23, "Goblet cell")@assays$SAVER$data)


pseudobulk <- cbind(ent, oth, gob) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk5.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)
```


```{r paper 2 SAVER ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.matrix(df_samp@assays$SAVER$data)

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
head(cell_ref)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVER_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)
```




paper 3
```{r paper 3 pseudobulks no imputation}
df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/full_df3_withALRA.rds")

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
"Proliferative cell              Other                EEC          Tuft cell         Enterocyte 
              5444                198                480                544               6110 
       Goblet cell              BEST4 
              3505                685"


#We will be making 5 pseudobulks total with 2000 cells total - refer to code for ground truth values of cell type proportions
#1
ent <- data.frame(samp2(pseudo, 1000, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 300, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$RNA$data)
eec <- data.frame(samp2(pseudo, 100, 23, "EEC")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pb1 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)

#2
ent <- data.frame(samp2(pseudo, 200, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 1000, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 400, 23, "Proliferative cell")@assays$RNA$data)
eec <- data.frame(samp2(pseudo, 100, 23, "EEC")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p2 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)



#3
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 700, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 400, 23, "Proliferative cell")@assays$RNA$data)
eec <- data.frame(samp2(pseudo, 100, 23, "EEC")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p3 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)




#4
ent <- data.frame(samp2(pseudo, 1500, 23, "Enterocyte")@assays$RNA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$RNA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$RNA$data)
eec <- data.frame(samp2(pseudo, 50, 23, "EEC")@assays$RNA$data)
b4 <- data.frame(samp2(pseudo, 50, 23, "BEST4")@assays$RNA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p4 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)




#5
ent <- data.frame(samp2(pseudo, 1800, 23, "Enterocyte")@assays$RNA$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$RNA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$RNA$data)

pseudobulk <- cbind(ent, gob, prol) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p5 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)

names(pb1)[names(pb1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- pb1 %>%
  inner_join(p2, by = "SYMBOL") %>% 
  inner_join(p3, by = "SYMBOL") %>% 
  inner_join(p4, by = "SYMBOL") %>% 
  inner_join(p5, by = "SYMBOL")

write.table(full_df,
            file = "C:/Users/14404/UW/BRAD HANSEN - data for deconv/Paper revision materials/DATA/cpm/GUT/gut_pseudobulks/ALLpseudos_Paper3_NoImp.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


```


```{r paper 3 no imputation ref matrix}

a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(object = df_samp, layer = "data"))


#need to rename genes from ensembl to gene names
ens <- rownames(b)
b$GENEID <- rownames(b)

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

ens_to_symbol_biomart <- merge(
  x = as.data.frame(ens),
  y =  ens_to_symbol_biomart ,
  by.y = 'ensembl_gene_id',
  all.x = TRUE,
  by.x = 'ens')

b <- merge(b, ens_to_symbol_biomart, by.x = "GENEID", by.y = "ens", all.x = TRUE)

b$GENEID <- NULL

#removing any NAs, averaging duplicated genes later below
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
b <- b %>%
      na.omit() %>%
      filter(hgnc_symbol != "")

rownames(b) <- b$hgnc_symbol
b$hgnc_symbol <- NULL

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)
cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_NoImputation_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)


```

```{r Paper 3 ALRA pseudobulks}

df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/full_df3_withALRA.rds")

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))

"Proliferative cell              Other                EEC          Tuft cell         Enterocyte 
              5444                198                480                544               6110 
       Goblet cell              BEST4 
              3505                685"


#We will be making 5 pseudobulks total with 2000 cells total - refer to code for ground truth values of cell type proportions
#1
ent <- data.frame(samp2(pseudo, 1000, 23, "Enterocyte")@assays$ALRA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$ALRA$data)
gob <- data.frame(samp2(pseudo, 300, 23, "Goblet cell")@assays$ALRA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 300, 23, "Proliferative cell")@assays$ALRA$data)
eec <- data.frame(samp2(pseudo, 100, 23, "EEC")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pb1 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)



#2
ent <- data.frame(samp2(pseudo, 200, 23, "Enterocyte")@assays$ALRA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$ALRA$data)
gob <- data.frame(samp2(pseudo, 1000, 23, "Goblet cell")@assays$ALRA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 400, 23, "Proliferative cell")@assays$ALRA$data)
eec <- data.frame(samp2(pseudo, 100, 23, "EEC")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p2 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)




#3
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$ALRA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$ALRA$data)
gob <- data.frame(samp2(pseudo, 700, 23, "Goblet cell")@assays$ALRA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 400, 23, "Proliferative cell")@assays$ALRA$data)
eec <- data.frame(samp2(pseudo, 100, 23, "EEC")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 100, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p3 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)



#4
ent <- data.frame(samp2(pseudo, 1500, 23, "Enterocyte")@assays$ALRA$data)
oth <- data.frame(samp2(pseudo, 100, 23, "Other")@assays$ALRA$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$ALRA$data)
tuft <- data.frame(samp2(pseudo, 100, 23, "Tuft cell")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$ALRA$data)
eec <- data.frame(samp2(pseudo, 50, 23, "EEC")@assays$ALRA$data)
b4 <- data.frame(samp2(pseudo, 50, 23, "BEST4")@assays$ALRA$data)

pseudobulk <- cbind(ent, oth, gob, tuft, prol, eec, b4) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p4 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)


#5
ent <- data.frame(samp2(pseudo, 1800, 23, "Enterocyte")@assays$ALRA$data)
gob <- data.frame(samp2(pseudo, 100, 23, "Goblet cell")@assays$ALRA$data)
prol <- data.frame(samp2(pseudo, 100, 23, "Proliferative cell")@assays$ALRA$data)

pseudobulk <- cbind(ent, gob, prol) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#need to rename genes from ensembl to gene names
#Mapping geneid to ensembl
ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = pseudobulk$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

#Adding it to the counts data
pseudobulk <- pseudobulk %>%
  left_join(ensembl_map, by = c("GENEID" = "ENSEMBL"))


pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
p5 <- pseudobulk %>%
      na.omit() %>%
      group_by(SYMBOL) %>%
      summarise(avg = mean(avg)) %>%
      relocate(SYMBOL)

names(pb1)[names(pb1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- pb1 %>%
  inner_join(p2, by = "SYMBOL") %>% 
  inner_join(p3, by = "SYMBOL") %>% 
  inner_join(p4, by = "SYMBOL") %>% 
  inner_join(p5, by = "SYMBOL")

write.table(full_df,
            file = "C:/Users/14404/UW/BRAD HANSEN - data for deconv/Paper revision materials/DATA/cpm/GUT/gut_pseudobulks/ALLpseudos_Paper3_ALRA.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


```

```{r Paper 3 ALRA cell ref}
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(df_samp@assays$ALRA$data)


#need to rename genes from ensembl to gene names
ens <- rownames(b)
b$GENEID <- rownames(b)

ensembl_map <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = b$GENEID,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

b <- merge(b, ensembl_map, by.x = "GENEID", by.y = "ENSEMBL", all.x = TRUE)

b$GENEID <- NULL


b1 <- b %>%
      na.omit() %>%
      group_by(SYMBOL) %>% 
      summarise(across(where(is.numeric), mean)) %>% 
      data.frame()

rownames(b1) <- b1$SYMBOL
b1$SYMBOL <- NULL
b <- b1

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)
cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "C:/Users/14404/UW/BRAD HANSEN - data for deconv/Paper revision materials/DATA/cpm/GUT/Gut_cellRefs/Paper3_ALRA_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

across(where(is.numeric(max(cell_ref))))
```



```{r paper 3 SAVER}

df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/paper3_cpm.rds")

saver_df <- readRDS("~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/Paper3_cpm_SAVERoutput.rds")


saver_df1 <- saver_df[["estimate"]]
saver_cells <- colnames(saver_df1)
df <- df[, saver_cells]
df[["SAVER"]] <- CreateAssayObject(data = saver_df1)


#memory saver
rm(saver_df, saver_cells, saver_df1)

#Need to make a "cell_type" column in metadata for below function to work
df$cell_type <- df@active.ident

#sample from data layer
df_samp <- samp(df, 300, 23)
table(Idents(df_samp))

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(df)[!(colnames(df) %in% colnames(df_samp))]
pseudo <- df[, cells_for_pseudo]

#memory saver
rm(df)
gc()

table(Idents(pseudo))
"Proliferative cell         Enterocyte        Goblet cell              BEST4 
              1565               1860               1006                 16 "


#We will be making 5 pseudobulks total with 1000 cells total - refer to code for ground truth values of cell type proportions. No Best4s will be included.
#1
ent <- data.frame(samp2(pseudo, 500, 23, "Enterocyte")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 250, 23, "Goblet cell")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 250, 23, "Proliferative cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, gob, prol) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

ens_to_symbol_biomart <- merge(
  x = as.data.frame(ens),
  y =  ens_to_symbol_biomart ,
  by.y = 'ensembl_gene_id',
  all.x = TRUE,
  by.x = 'ens')

pseudobulk <- merge(pseudobulk, ens_to_symbol_biomart, by.x = "GENEID", by.y = "ens", all.x = TRUE)
pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(hgnc_symbol) %>%
      summarise(avg = mean(avg)) %>%
      relocate(hgnc_symbol) %>%
      filter(hgnc_symbol != "")

write.table(pseudobulk, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk1.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2
ent <- data.frame(samp2(pseudo, 100, 23, "Enterocyte")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 450, 23, "Goblet cell")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 450, 23, "Proliferative cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, gob, prol) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

ens_to_symbol_biomart <- merge(
  x = as.data.frame(ens),
  y =  ens_to_symbol_biomart ,
  by.y = 'ensembl_gene_id',
  all.x = TRUE,
  by.x = 'ens')

pseudobulk <- merge(pseudobulk, ens_to_symbol_biomart, by.x = "GENEID", by.y = "ens", all.x = TRUE)
pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(hgnc_symbol) %>%
      summarise(avg = mean(avg)) %>%
      relocate(hgnc_symbol) %>%
      filter(hgnc_symbol != "")

write.table(pseudobulk, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk2.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#3
ent <- data.frame(samp2(pseudo, 250, 23, "Enterocyte")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 400, 23, "Goblet cell")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 350, 23, "Proliferative cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, gob, prol) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

ens_to_symbol_biomart <- merge(
  x = as.data.frame(ens),
  y =  ens_to_symbol_biomart ,
  by.y = 'ensembl_gene_id',
  all.x = TRUE,
  by.x = 'ens')

pseudobulk <- merge(pseudobulk, ens_to_symbol_biomart, by.x = "GENEID", by.y = "ens", all.x = TRUE)
pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(hgnc_symbol) %>%
      summarise(avg = mean(avg)) %>%
      relocate(hgnc_symbol) %>%
      filter(hgnc_symbol != "")

write.table(pseudobulk, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk3.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4
ent <- data.frame(samp2(pseudo, 750, 23, "Enterocyte")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 125, 23, "Goblet cell")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 125, 23, "Proliferative cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, gob, prol) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

ens_to_symbol_biomart <- merge(
  x = as.data.frame(ens),
  y =  ens_to_symbol_biomart ,
  by.y = 'ensembl_gene_id',
  all.x = TRUE,
  by.x = 'ens')

pseudobulk <- merge(pseudobulk, ens_to_symbol_biomart, by.x = "GENEID", by.y = "ens", all.x = TRUE)
pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(hgnc_symbol) %>%
      summarise(avg = mean(avg)) %>%
      relocate(hgnc_symbol) %>%
      filter(hgnc_symbol != "")

write.table(pseudobulk, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk4.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

#5
ent <- data.frame(samp2(pseudo, 900, 23, "Enterocyte")@assays$SAVER$data)
gob <- data.frame(samp2(pseudo, 50, 23, "Goblet cell")@assays$SAVER$data)
prol <- data.frame(samp2(pseudo, 50, 23, "Proliferative cell")@assays$SAVER$data)

pseudobulk <- cbind(ent, gob, prol) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



#need to rename genes from ensembl to gene names
ens <- pseudobulk$GENEID

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

ens_to_symbol_biomart <- merge(
  x = as.data.frame(ens),
  y =  ens_to_symbol_biomart ,
  by.y = 'ensembl_gene_id',
  all.x = TRUE,
  by.x = 'ens')

pseudobulk <- merge(pseudobulk, ens_to_symbol_biomart, by.x = "GENEID", by.y = "ens", all.x = TRUE)
pseudobulk$GENEID <- NULL

#removing any NAs, averaging duplicated genes
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
pseudobulk <- pseudobulk %>%
      na.omit() %>%
      group_by(hgnc_symbol) %>%
      summarise(avg = mean(avg)) %>%
      relocate(hgnc_symbol) %>%
      filter(hgnc_symbol != "")

write.table(pseudobulk, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk5.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

```


```{r Paper 3 SAVER cell ref}
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(df_samp@assays$SAVER$data)


#need to rename genes from ensembl to gene names
ens <- rownames(b)
b$GENEID <- rownames(b)

mart <- useDataset('hsapiens_gene_ensembl', useMart('ensembl'))
ens_to_symbol_biomart <- getBM(
  filters = 'ensembl_gene_id',
  attributes = c('ensembl_gene_id', 'hgnc_symbol'),
  values = ens,
  mart = mart)

ens_to_symbol_biomart <- merge(
  x = as.data.frame(ens),
  y =  ens_to_symbol_biomart ,
  by.y = 'ensembl_gene_id',
  all.x = TRUE,
  by.x = 'ens')

b <- merge(b, ens_to_symbol_biomart, by.x = "GENEID", by.y = "ens", all.x = TRUE)

b$GENEID <- NULL

#removing any NAs, averaging duplicated genes later below
#for some reason there is a blank gene named "", I will remove this in the last line of the below code
b <- b %>%
      na.omit() %>%
      filter(hgnc_symbol != "")

rownames(b) <- b$hgnc_symbol
b$hgnc_symbol <- NULL

#b[c(1:10), c(1:10)]
t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

colnames(b) <-gsub(".", "-", colnames(b), fixed = TRUE)
cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_CellRef_cpm.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)
```




```{r condensing pseudobulks to one file - paper 1}
#Paper 1 - no imputation
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_NoImputation_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")

write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Allpseudos_Paper1_NoImp.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)

#Paper 1 - ALRA imputation
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_ALRA_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")

write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Allpseudos_Paper1_ALRA.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


#Paper 1 - SAVER
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Paper1_SAVER_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")

write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Allpseudos_Paper1_SAVER.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


#Paper 1 - MAGIC
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/df1_MAGIC_pb1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/df1_MAGIC_pb2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/df1_MAGIC_pb3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/df1_MAGIC_pb4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/df1_MAGIC_pb5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")

write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper1/refs_and_pseudos/Allpseudos_Paper1_MAGIC.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)



```


```{r condensing pseudobulks to one file - paper 2}

#Paper 2 - No imputation
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_NoImputation_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")

write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/ALLpseudos_Paper2_NoImp.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


#Paper 2 - ALRA
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_ALRA_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")


write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/ALLpseudos_Paper2_ALRA.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)

#Paper 2 - SAVER
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/Paper2_SAVERimputation_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")


write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/ALLpseudos_Paper2_SAVER.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


#Paper2 MAGIC
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/df2_MAGIC_pb1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/df2_MAGIC_pb2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/df2_MAGIC_pb3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/df2_MAGIC_pb4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/df2_MAGIC_pb5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "GENEID") %>% 
  inner_join(p3, by = "GENEID") %>% 
  inner_join(p4, by = "GENEID") %>% 
  inner_join(p5, by = "GENEID")


write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Proximal to distal survey/refs_and_pseudos/ALLpseudos_Paper2_MAGIC.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


```


```{r condensing pseudobulks to one file - paper 3}

#Paper 3 - No imputation
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_NoImputation_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_NoImputation_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_NoImputation_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_NoImputation_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_NoImputation_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "hgnc_symbol") %>% 
  inner_join(p3, by = "hgnc_symbol") %>% 
  inner_join(p4, by = "hgnc_symbol") %>% 
  inner_join(p5, by = "hgnc_symbol")


write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Allpseudos_Paper3_NoImp.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)

#Paper 3 - ALRA
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_ALRA_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_ALRA_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_ALRA_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_ALRA_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_ALRA_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "hgnc_symbol") %>% 
  inner_join(p3, by = "hgnc_symbol") %>% 
  inner_join(p4, by = "hgnc_symbol") %>% 
  inner_join(p5, by = "hgnc_symbol")


write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Allpseudos_Paper3_ALRA.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)


#Paper 3 - SAVER
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Paper3_SAVER_pseudobulk5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "hgnc_symbol") %>% 
  inner_join(p3, by = "hgnc_symbol") %>% 
  inner_join(p4, by = "hgnc_symbol") %>% 
  inner_join(p5, by = "hgnc_symbol")


write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Allpseudos_Paper3_SAVER.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)



#Paper 3 MAGIC
p1 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/df3_MAGIC_pb1.txt")
p2 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/df3_MAGIC_pb2.txt")
p3 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/df3_MAGIC_pb3.txt")
p4 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/df3_MAGIC_pb4.txt")
p5 <- read.delim(file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/df3_MAGIC_pb5.txt")

names(p1)[names(p1) == "avg"] <- "pseudo1"
names(p2)[names(p2) == "avg"] <- "pseudo2"
names(p3)[names(p3) == "avg"] <- "pseudo3"
names(p4)[names(p4) == "avg"] <- "pseudo4"
names(p5)[names(p5) == "avg"] <- "pseudo5"

full_df <- p1 %>%
  inner_join(p2, by = "name") %>% 
  inner_join(p3, by = "name") %>% 
  inner_join(p4, by = "name") %>% 
  inner_join(p5, by = "name")


write.table(full_df, 
            file = "~/Dissertation project research/Experiment planning & results/Deconvolution/Paper 3/refs_and_pseudobulks/Allpseudos_Paper3_MAGIC.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = T)




```





