---
title: "Testis_Deconv_mergethemerges"
author: "BH"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readxl, ggplot2, ggsci, ggthemes, vroom, readr, tidyverse, DWLS, stringr, janitor, ggridges)

theme_set(theme_few() + theme(text = element_text(size=28, family="Myriad Pro")))

```

Load the merged files

```{r load cell refs}
### Make RIDGE plots for each gene

# need to load in each reference

fp <- ("~/OneDrive - UW/data for deconv/Testis_cellRefs/ridges")
files <- list.files(path = fp, pattern = "*.txt", full.names = TRUE)

gene_df <- list()

for (file in files) {
  
  basename_file <- basename(file)
  method_value <- str_extract(basename_file, "(?<=_)[^_]+(?=\\.txt$)")
  ref <- str_remove(basename_file, paste0("_", method_value, "\\.txt$"))
  
  df <- read.delim(file, header = FALSE) %>%
  t() %>%
  row_to_names(row_number = 1) %>%
  as.data.frame() %>%
  select(Cyp11a1, Dazl, Ddx4, Inhba, Sox9, clusterID) %>%
  mutate(
    method = method_value,
    ref = ref,
    type = clusterID,  
    method = recode(method, "SVR" = "SAVER", "MAGICref" = "MAGIC", "noIMP" = "No Imp."),  
    type = recode(type, "Stroma/Leydig" = "Leydig", "Pro-SG/SSC" = "Germ", "SSCs" = "Germ"),  
    across(c(Cyp11a1, Dazl, Ddx4, Inhba, Sox9), as.numeric),  
    across(c(Cyp11a1, Dazl, Ddx4, Inhba, Sox9), ~ log2(. + 1)),
    Species = case_when(
      tolower(substr(ref, 1, 1)) == "m" ~ "Mouse",  
      tolower(substr(ref, 1, 1)) == "h" ~ "Human"))


  gene_df[[length(gene_df) + 1]] <- df
}

gene_plots <- bind_rows(gene_df)

gene_plots$method <- factor(gene_plots$method, levels = c("No Imp.", "ALRA", "SAVER", "MAGIC"))

```







Adult H plotting

```{r plotting112}
gene_plots <- gene_plots %>% filter(ref != 'm_d7_DIFF')

input <- gene_plots %>% filter(type == 'Sertoli' | type == 'Germ' | type == 'Leydig' )

genelist <- c("Cyp11a1", "Dazl", "Ddx4","Inhba","Sox9")

for (gene in genelist) {
  
  ridge <- ggplot(data=input, aes(x = get(gene), y = type, fill = Species)) +
    geom_density_ridges(alpha = 0.65, scale = 1.1) +
    scale_y_discrete(expand = expansion(add = c(0.05, 1.2))) +
    ylab(gene) +  
    xlab("logCPM") +
    coord_cartesian(clip = "off") +
    theme_bw(28, base_family = "Myriad Pro") +
    scale_fill_d3() +  
    theme(legend.position = "bottom") +
    theme(axis.title.y=element_text(face="italic"), base_family = "Myriad Pro")+
    facet_wrap(~method, nrow = 1)

  output_file <- paste0("~/OneDrive - UW/data for deconv/Deconvolution output (F)/Testis/ridgeplots/testis_", gene, "_ridge.png")
  ggsave(ridge, dpi = 600, filename = output_file, width = 14, height = 7)
  
}

```


