---
title: "GUT-crosscompare_DWLS-MAGICS"
author: "BH"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readxl, ggplot2, ggsci, ggthemes, vroom,tools, readr, tidyverse, DWLS, stringr, Metrics)

theme_set(theme_few() + theme(text = element_text(size=28, family="Myriad Pro")))

```



Load the signatures matrices
FOR GUT USE DWLS-ALRA FOR EACH REFERENCE
FOR GUT USE OLS-ALRA FOR EACH REFERENCE
FOR GUT USE DLWS-noIMP FOR EACH REFERENCE


```{r sigs}


swd <- list.dirs("~/OneDrive - UW/data for deconv/Signature matrices impute+no impute (D)/DWLS_sigmatrix/", full.names = TRUE)

# Initialize an empty list to hold sublists for each type
all_matrices <- list()

type <- c("noim", "alra", "saver", "magic")

for (dir in swd) {

    for (t in type) {
        if (grepl(t, dir)) {
        
            if (is.null(all_matrices[[t]])) {
                all_matrices[[t]] <- list()
            }
            
            rds_files <- list.files(dir, pattern = "Sig.rds", full.names = TRUE, recursive = TRUE)
            
            for (rds_file in rds_files) {
            
                data <- readRDS(rds_file)
                file_name_part <- basename(dirname(rds_file))
                new_name <- paste0(t, "_", file_name_part, "_sig")
                all_matrices[[t]][[new_name]] <- data   }} }}

```


```{r deconv draft cross, include=FALSE}

gutrnaseq <- read.delim("~/OneDrive - UW/data for deconv/rna-seq data (A)/enteroid_RNAseq_cpm.txt")%>% column_to_rownames('GENEID')

  DWLS <- data.frame()
  SVR <- data.frame()
  OLS <- data.frame()


runDWLSall <- function(df_in, sig_matrix_in) {
  rows <- intersect(rownames(sig_matrix_in), rownames(df_in))
  
  df <- df_in[rows, ]
  sig_matrix_in <- sig_matrix_in[rows, ]
  
  samples <- colnames(df)
  
  for (i in samples) {
    name <- i
    dataBulk <- as.numeric(df[, i])
    Signature <- as.matrix(sig_matrix_in)
    Signature <- 2^Signature - 1  
    
    solDWLS <- solveDampenedWLS(Signature, dataBulk)
    solOLS <- solveOLS(Signature, dataBulk)
    
    DWLS <- rbind(DWLS, solDWLS)
    OLS <- rbind(OLS, solOLS)
  }
  
  # Ensure correct column names and add method columns before binding results
  colnames(DWLS) <- c(colnames(Signature))
  DWLS$method <- 'DWLS'
  
  colnames(OLS) <- c(colnames(Signature))
  OLS$method <- 'OLS'

  out <- rbind(DWLS, OLS)
  out$ref <- rep(samples, times = 2)

  return(out)
}


alra_gut <- lapply(all_matrices$alra, runDWLSall, df_in = gutrnaseq)


alra_result <- lapply(names(alra_gut), function(name) {
  df <- alra_gut[[name]] 
  df$title <- name  
  df$imp <- 'ALRA'
  return(df)
})


noim_gut <- lapply(all_matrices$noim, runDWLSall, df_in = gutrnaseq)

noim_result <- lapply(names(noim_gut), function(name) {
  df <- noim_gut[[name]] 
  df$title <- name  
  df$imp <- 'No imp.'
  return(df)
})


gut_metadata <- read_xlsx('~/OneDrive - UW/data for deconv/rna-seq data (A)/gut_metadata.xlsx')

all_gut_deconv <- bind_rows(noim_result,alra_result)%>% left_join(gut_metadata ,by='ref') %>% mutate(id = paste0(method,'-',imp),
                                                                                                     name = paste0(donor,'-',diff))%>%
  filter(id == 'DWLS-ALRA' |id == 'OLS-ALRA' |id == 'DWLS-No imp.'  )

saveRDS(all_gut_deconv, "~/OneDrive - UW/data for deconv/Deconvolution output (F)/GUT_outputfileDECONV.rds")

all_gut_deconv <- readRDS("~/OneDrive - UW/data for deconv/Deconvolution output (F)/GUT_outputfileDECONV.rds")

plot_gut <- all_gut_deconv %>% select(-c(Gobletcell, BEST4, Tuftcell, EEC, Panethcell)) %>% pivot_longer(cols = c(Enterocyte, Other, Proliferativecell), names_to = 'celltype', values_to = "expression")%>% mutate(sig =  sub("^[^_]+_([^_]+)_.*$", "\\1", title))%>%
  mutate(sig = recode(sig, 'df1' = "Gut Atlas", 'df2' = "GSE185", 'df3' = 'GSE201'))%>% mutate(plot = if_else(expression < 0, 0, expression))%>%mutate(celltype = recode(celltype, 'Proliferativecell' = "Proliferative cell"))

plot_gut$diff <- factor(plot_gut$diff, levels = c("Undiff.", "Diff."))

write.csv(plot_gut, "~/OneDrive - UW/data for deconv/Deconvolution output (F)/Gut_updated/gut_bulkdeconv.csv")

```

Load the signatures matrices
FOR GUT USE DWLS-ALRA FOR EACH REFERENCE
FOR GUT USE OLS-ALRA FOR EACH REFERENCE
FOR GUT USE DLWS-noIMP FOR EACH REFERENCE

plotting the gut

```{r plotting GUT}
plots6 <- ggplot(data=plot_gut, aes(x=diff, y=plot, fill=celltype)) +
  geom_boxplot(alpha = 0.45, outliers = FALSE) + 
  geom_jitter(aes(x=diff, y=plot, fill=celltype, shape = donor, color=celltype),  position = position_dodge(width = 0.5),  size = 3, alpha = 0.8) +  
  scale_y_continuous(name="Cell Proportion", breaks = c(0, 0.25, 0.5, 0.75, 1.0), limits = c(0,1))+
  scale_fill_d3()+
  scale_color_d3()+
  labs(shape="Reference Source", color= "Cell Type")+
  xlab(" ")+
  guides(fill = "none")+
  theme(legend.position="right", axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~id)



plots6

ggsave(plots6, dpi = 600, filename = "~/OneDrive - UW/data for deconv/Deconvolution output (F)/Gut/GUT-bulkDeconv.png", width = 14, height=9, units = 'in')

```

```{r plotting GUT2}
plots7 <- ggplot(data = plot_gut, aes(x = diff, y = plot, fill = celltype)) +
  # Boxplot with position_dodge to align by celltype
  geom_boxplot(alpha = 0.45, outliers = FALSE, position = position_dodge(width = 0.8)) + 
  # Jittered points aligned over the boxplots
  geom_jitter(aes(x = diff, y = plot, fill = celltype, shape = sig, color = celltype),
              position = position_dodge(width = 0.8),  # Same dodge width as boxplot
              size = 4, alpha = 0.8) +  
  # Y axis scale
  scale_y_continuous(name = "Cell Proportion", breaks = c(0, 0.25, 0.5, 0.75, 1.0), limits = c(0, 1)) +
  # Color scales
  scale_fill_d3() +
  scale_color_d3() +
  # Labels
  labs(shape = "Reference", color = "Cell Type") +
  xlab(" ") +
  guides(fill = "none") +
  # Theme
  theme(legend.position = "right", axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~donor+id)





plots7

ggsave(plots7, dpi = 600, filename = "~/OneDrive - UW/data for deconv/Deconvolution output (F)/Gut/GUT-bulkDeconv-bydonor.png", width = 16, height=15, units = 'in')

```



