---
title: "testis-crosscompare_DWLS"
author: "BH"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readxl, ggplot2, ggsci, ggthemes, vroom, readr, tidyverse, DWLS, stringr, Metrics, quadprog)

theme_set(theme_few() + theme(text = element_text(size=28, family="Myriad Pro")))

```

load objects
```{r objects, eval=FALSE, include=FALSE}

human_to_rat <- readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Human.rds")
# Keep only the Gene Names
human_to_rat <- human_to_rat[,c("Human_GRCh38_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(human_to_rat) <- c("human","rat")
human_to_rat <- human_to_rat %>% distinct()

Rat_to_Mouse <- readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Mouse.rds")
# Keep only the Gene Names
Rat_to_Mouse <- Rat_to_Mouse[,c("Mouse_GRCm39_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(Rat_to_Mouse) <- c("mouse","rat")
Rat_to_Mouse <- Rat_to_Mouse %>% distinct()

files_out <- "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/combined/"




```


Load in each methods combined psuedobulk (all magics, all alras, etc.). Then run dWLS deconv on those and remove the same-same comparisons. Only use the D7 same label files

load the PBs
```{r load PBs}

noIMP_pbs <- read.delim('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/cpm/Testis/PBs/all_noimp_PBs.txt')%>% select(-matches("diff"))%>%rename(m_n_d7_NoImp_srt10 = m_n_d7_d2_NoImp_srt10)

alra_pbs <- read.delim('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/cpm/Testis/PBs/all_ALRA_PBs.txt')%>% select(-matches("diff"))

saver_pbs <- read.delim('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/cpm/Testis/PBs/all_SAVER_PBs.txt')%>% select(-matches("diff"))%>%rename_with(~ str_replace_all(., "SVR", "SAVER"))

magic_pbs <- read.delim('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/cpm/Testis/PBs/MAGIC/allPB_MAGIC_combined.txt')%>%rename_with(~ str_replace_all(., "SAVER", "MAGIC"))
colnames(magic_pbs)[colnames(magic_pbs) == "rat"] = "gene"


germ_cols <- c("d_spg", "SSCs", "Germ", "ProSGSSC", "Pro")
leydig_cols <- c("Leydig", "StromaLeydig")



unlist_func <- function(list) {bind_rows(lapply(names(list), function(name) {
    df <- list[[name]]
    df$source <- name
    existing_germ_cols <- germ_cols[germ_cols %in% names(df)]
    existing_lc_cols <- leydig_cols[leydig_cols %in% names(df)]


  refs <- unlist(strsplit(name, "_"))  
  df %>%
    mutate(#pb = sapply(strsplit(refs, "_"), `[`, 1),
           #pbref = sapply(strsplit(refs, "_"), `[`, 2),
          source = name,
           imp = refs[1],
           sigref = refs[2],
          germ_all = rowSums(across(all_of(existing_germ_cols)), na.rm = TRUE),
          lc_all = rowSums(across(all_of(existing_lc_cols)), na.rm = TRUE)) %>%
  select(-all_of(existing_germ_cols)) %>% select(-all_of(existing_lc_cols))
  }))}




```


Load the signatures matrices
```{r sigs}
#important to use the corrected folder

swd <- list.dirs("~/OneDrive - UW/data for deconv/Signature matrices impute+no impute (D)/Testis/DWLS_testis/alldata_revision_04132025/", full.names = TRUE)

# Initialize an empty list to hold sublists for each type
all_matrices <- list()

type <- c("noIMP", "ALRA", "SAVER", "MAGIC")

for (dir in swd) {

    for (t in type) {
        if (grepl(t, dir)) {
        
            if (is.null(all_matrices[[t]])) {
                all_matrices[[t]] <- list() }
            
            rds_files <- list.files(dir, pattern = "Sig.rds", full.names = TRUE, recursive = TRUE)
            
            for (rds_file in rds_files) {
            
                data <- readRDS(rds_file)
                file_name_part <- basename(dirname(rds_file))
                new_name <- paste0(t, "_", file_name_part, "_sig")
                all_matrices[[t]][[new_name]] <- data   }} }}

```

```{r svr}


SVR <- data.frame()


runSVRall <- function(df_in, sig_matrix_in) {
  
  df <- df_in %>% column_to_rownames('gene')
  rows <- intersect(rownames(sig_matrix_in), rownames(df))
  df <- df[rows, ]
  sig_matrix_in <- sig_matrix_in[rows, ]
  sig_matrix_in <- sig_matrix_in[, !(colnames(sig_matrix_in) %in% c("Endo", "Immune", "meiosis_spcs"))]

  
  samples <- colnames(df)
  
  for (i in samples) {
    name <- i
    dataBulk <- as.numeric(df[, i])
    Signature <- as.matrix(sig_matrix_in)

    solSVR <- solveSVR(Signature, dataBulk)
    

    SVR <- rbind(SVR, solSVR)
  }

  colnames(SVR) <- c(colnames(Signature))
  SVR$method <- 'SVR'
  

  out <- rbind(SVR)
  out$ref <- samples

  return(out)
}

alra_SVR <- unlist_func(lapply(all_matrices$ALRA, runSVRall, df_in = alra_pbs))%>% mutate(method='SVR')
noIMP_SVR <- unlist_func(lapply(all_matrices$noIMP, runSVRall, df_in = noIMP_pbs))%>% mutate(method='SVR')
saver_SVR <- unlist_func(lapply(all_matrices$SAVER, runSVRall, df_in = saver_pbs))%>% mutate(method='SVR')
magic_SVR <- unlist_func(lapply(all_matrices$MAGIC, runSVRall, df_in = magic_pbs))%>% mutate(method='SVR')%>% select(-Stroma)

SVR_testis <- rbind(alra_SVR,noIMP_SVR,saver_SVR,magic_SVR) 

```


```{r ols}

OLS <- data.frame()

runOLSall <- function(df_in, sig_matrix_in) {
  df <- df_in %>% column_to_rownames('gene')

  rows <- intersect(rownames(sig_matrix_in), rownames(df))
  df <- df[rows, ]
  sig_matrix_in <- sig_matrix_in[rows, ]
  sig_matrix_in <- sig_matrix_in[, !(colnames(sig_matrix_in) %in% c("Endo", "Immune", "meiosis_spcs"))]

  samples <- colnames(df)
  results_matrix <- matrix(NA, nrow = length(samples), ncol = ncol(sig_matrix_in))
  rownames(results_matrix) <- samples
  colnames(results_matrix) <- colnames(sig_matrix_in)

  
  solveOLS <- function(S, B) {
    D <- t(S) %*% S
    d <- t(S) %*% B
    A <- cbind(diag(dim(S)[2]))
    bzero <- rep(-1E-2, dim(S)[2])
    solution<-solve.QP(D,d,A,bzero)$solution
    names(solution)<-colnames(S)
    print(round(solution/sum(solution),5))
   return(solution/sum(solution))
  }

  for (i in seq_along(samples)) {
    sample_name <- samples[i]
    B <- as.numeric(df[, sample_name])
    S <- as.matrix(sig_matrix_in)

    # actual deconv
    result <- solveOLS(S, B)
    results_matrix[sample_name, ] <- result
  }
  
  results_df <- as.data.frame(results_matrix)
  return(results_df)
}



alra_OLS <- unlist_func(lapply(all_matrices$ALRA, runOLSall, df_in = alra_pbs))
noIMP_OLS <- unlist_func(lapply(all_matrices$noIMP, runOLSall, df_in = noIMP_pbs))
saver_OLS <- unlist_func(lapply(all_matrices$SAVER, runOLSall, df_in = saver_pbs))
magic_OLS <- unlist_func(lapply(all_matrices$MAGIC, runOLSall, df_in = magic_pbs))%>% select(-Stroma)


ols_testis <- rbind(alra_OLS,noIMP_OLS,saver_OLS,magic_OLS)%>% mutate(method='ols')%>% rownames_to_column('ref')



```



```{r DWLS}

runDWLSall <- function(df_in, sig_matrix_in) {
  # Convert gene column to rownames
  df <- df_in %>% column_to_rownames('gene')

  # Intersect genes
  rows <- intersect(rownames(sig_matrix_in), rownames(df))
  df <- df[rows, ]
  sig_matrix <- sig_matrix_in[rows, ]
  sig_matrix <- sig_matrix[, !(colnames(sig_matrix) %in% c("Endo", "Immune", "meiosis_spcs"))]

  samples <- colnames(df)
  results_matrix <- matrix(NA, nrow = length(samples), ncol = ncol(sig_matrix))
  rownames(results_matrix) <- samples
  colnames(results_matrix) <- colnames(sig_matrix)

  solveOLSInternal<-function(S,B){
  D<-t(S)%*%S
  d<-t(S)%*%B
  A<-cbind(diag(dim(S)[2]))
  bzero<-c(rep(-0.01,dim(S)[2]))
  solution<-solve.QP(D,d,A,bzero)$solution
  names(solution)<-colnames(S)
  return(solution)
}
  #this is from DWLS github
solveDampenedWLS<-function(S,B){
  #first solve OLS, use this solution to find a starting point for the weights
  solution<-solveOLSInternal(S,B)
  #now use dampened WLS, iterate weights until convergence
  iterations<-0
  changes<-c()
  #find dampening constant for weights using cross-validation
  j<-findDampeningConstant(S,B,solution)
  change<-1
  while(change>.01 & iterations<1000){
    newsolution<-solveDampenedWLSj(S,B,solution,j)
    #decrease step size for convergence
    solutionAverage<-rowMeans(cbind(newsolution,matrix(solution,nrow = length(solution),ncol = 4)))
    change<-norm(as.matrix(solutionAverage-solution))
    solution<-solutionAverage
    iterations<-iterations+1
    changes<-c(changes,change)
  }
  print(round(solution/sum(solution),5))
  return(solution/sum(solution))
}


  for (i in seq_along(samples)) {
    sample_name <- samples[i]
    B <- as.numeric(df[, sample_name])
    S <- as.matrix(sig_matrix)

#Actual deconv
    result <- solveDampenedWLS(S, B)

    # Store the result in the appropriate place
    results_matrix[sample_name, ] <- result
  }

  # Convert the matrix to a data frame
  results_df <- as.data.frame(results_matrix)
  return(results_df)
}



alra_dwls <- unlist_func(lapply(all_matrices$ALRA, runDWLSall, df_in = alra_pbs))
noIMP_dwls <- unlist_func(lapply(all_matrices$noIMP, runDWLSall, df_in = noIMP_pbs))
saver_dwls <- unlist_func(lapply(all_matrices$SAVER, runDWLSall, df_in = saver_pbs))
magic_dwls <- unlist_func(lapply(all_matrices$MAGIC, runDWLSall, df_in = magic_pbs))%>% select(-Stroma)


dwls_testis <- rbind(alra_dwls,noIMP_dwls,saver_dwls,magic_dwls)%>% mutate(method='dwls')%>% rownames_to_column('ref')



```



combine the objects
```{r combine all}

testis_deconvs <- rbind(dwls_testis,ols_testis, SVR_testis)%>%mutate(ref = str_remove(ref, "\\.\\.\\..*"))
testis_deconvs$sigref <- testis_deconvs$source

testis_deconvs <- testis_deconvs%>% select(-source)

saveRDS(testis_deconvs, '~/OneDrive - UW/data for deconv/Paper revision materials/testis_deconvs.rds')
```



add in the music + nnls files
```{r music file}

testis_music_results <- readRDS('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/TESTIS/music_results_testis.rds')

# h112_music,h120_music,h124_music,md2_music,md7_music

music_unlist <- function(i){
  

germ_cols <- c("d_spg", "SSCs", "Germ", "ProSGSSC", "Pro")
leydig_cols <- c("Leydig", "StromaLeydig")
extras <- c("Endo", 'meiosis_spcs', 'Immune')
    existing_germ_cols <- germ_cols[germ_cols %in% names(i)]
    existing_lc_cols <- leydig_cols[leydig_cols %in% names(i)]
    extra_cols <- extras[extras %in% names(i)]
    
  i %>%
    mutate(
          germ_all = rowSums(across(all_of(existing_germ_cols)), na.rm = TRUE),
          lc_all = rowSums(across(all_of(existing_lc_cols)), na.rm = TRUE)) %>%
  select(-all_of(existing_germ_cols)) %>% 
    select(-all_of(existing_lc_cols)) %>%
       select(-all_of(extra_cols))
  }



h112_music <- music_unlist(as.data.frame(testis_music_results[[1]]$Est.prop.weighted) %>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'h112', method = "music"))
h120_music <- music_unlist(as.data.frame(testis_music_results[[2]]$Est.prop.weighted)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'h120', method = "music"))
h124_music <- music_unlist(as.data.frame(testis_music_results[[3]]$Est.prop.weighted)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'h124', method = "music"))
md2_music <- music_unlist(as.data.frame(testis_music_results[[4]]$Est.prop.weighted)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'md2', method = "music"))
md7_music <- music_unlist(as.data.frame(testis_music_results[[5]]$Est.prop.weighted)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'md7', method = "music"))

h112_nnls <- music_unlist(as.data.frame(testis_music_results[[1]]$Est.prop.allgene)%>% rename_with(~ gsub("[-/]", "", .x)) %>% rownames_to_column('ref') %>% mutate(sigref = 'h112', method = "nnls"))
h120_nnls <- music_unlist(as.data.frame(testis_music_results[[2]]$Est.prop.allgene)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'h120', method = "nnls"))
h124_nnls <- music_unlist(as.data.frame(testis_music_results[[3]]$Est.prop.allgene)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'h124', method = "nnls"))
md2_nnls <- music_unlist(as.data.frame(testis_music_results[[4]]$Est.prop.allgene)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'md2', method = "nnls"))
md7_nnls <- music_unlist(as.data.frame(testis_music_results[[5]]$Est.prop.allgene)%>% rename_with(~ gsub("[-/]", "", .x))%>% rownames_to_column('ref') %>% mutate(sigref = 'md7', method = "nnls"))

all_music_testis <- rbind(h112_music,h120_music,h124_music,md2_music,md7_music,h112_nnls,h120_nnls,h124_nnls,md2_nnls,md7_nnls)%>% mutate(imp= 'noIMP')
# outputs are 
# Est.prop.weighted: data.frame of MuSiC estimated proportions, subjects by cell types;
# Est.prop.allgene: data.frame of NNLS estimated proportions, subjects by cell types


all_w_music <- rbind(testis_deconvs,all_music_testis)%>% select(-c(germ_all, PTM))



```


add in the cibersort data
```{r cibersortx}
# new magics
testis_cb <- read_excel("~/OneDrive - UW/data for deconv/Paper revision materials/DATA/cpm/Testis/MAGIC Cibersort/combined_cb_testis.xlsx")%>% select(-c(germ_all, PTM))

othercbs <- readRDS("~/OneDrive - UW/data for deconv/Deconvolution output (F)/Testis/all_testis_wCB.rds")%>% filter(imp != "MAGIC") %>% rename( ref = Mixture, sigref = REFbase, lc_all = Leydig) %>% select(-c(PBbase, trues, cell))%>% filter(method == "CIBERSORTx")%>%mutate(method = if_else(method == "CIBERSORTx", "cb", method)) %>%mutate(imp = if_else(imp == "No Imp.", "noIMP", imp))




all_testis <- rbind(all_w_music,testis_cb,othercbs) %>% 
  mutate(pb_paper = case_when(
    str_detect(ref, "112") ~ "h112",
    str_detect(ref, "120") ~ "h120",
    str_detect(ref, "124") ~ "h124",
    str_detect(ref, "d2") ~ "md2",
    str_detect(ref, "d7") ~ "md7"),
    sig_ref = case_when(
    str_detect(sigref, "112") ~ "h112",
    str_detect(sigref, "120") ~ "h120",
    str_detect(sigref, "124") ~ "h124",
    str_detect(sigref, "d2") ~ "md2",
    str_detect(sigref, "d7") ~ "md7"),
    pseudo = case_when(
    str_detect(ref, "10") ~ 0.10,
    str_detect(ref, "25") ~ 0.25,
    str_detect(ref, "50") ~ 0.50,
    str_detect(ref, "75") ~ 0.75,
    str_detect(ref, "90") ~ 0.90),
    prediction = case_when(
    str_detect(ref, "112") ~ lc_all,
    TRUE ~ Sertoli))%>%
      select(-c(ref, sigref))%>% mutate(comp = if_else(sig_ref == pb_paper, "intra", "inter"))


table(all_testis$sig_ref)

all_testis_sames <- filter(all_testis, comp =='intra')
all_testis_inter <- filter(all_testis, comp =='inter')

testis_results <- list(sames = all_testis_sames, inter = all_testis_inter)


saveRDS(testis_results, "~/OneDrive - UW/data for deconv/Paper revision materials/brad_updated_code/testis_results.rds")
```



```{r testis mapes}




table(all_testis_sames$method, all_testis_sames$imp)


mapes <-  all_testis_sames %>%  
            group_by(method, imp) %>%
            summarise(mape_value = mape(prediction, pseudo)) %>%
            mutate(percent = mape_value*100) %>%
            ungroup()

rmse <-  all_testis_sames %>%  
            group_by(method, imp) %>%
            summarise(rmse_value = rmse(prediction, pseudo)) %>%
            ungroup()



mape_minmax <-  all_testis_sames %>% 
 group_by(method, imp, sig_ref) %>%
  summarise(
    mape_value = mape(prediction, pseudo)) %>%
      ungroup()%>%
    group_by(method, imp) %>%
      summarise(
        min=min(mape_value)*100,
        max=max(mape_value)*100)

rmse_minmax <-  all_testis_sames %>% 
 group_by(method, imp, sig_ref) %>%
  summarise(
    rmse_value = rmse(prediction, pseudo)) %>%
      ungroup()%>%
    group_by(method, imp) %>%
      summarise(
        min=min(rmse_value),
        max=max(rmse_value))


testis_sames_mapes_rmse <- list(mapes,mape_minmax,rmse,rmse_minmax)


abs_mape <- function(pred, actual) {
  non_zero <- actual != 0
  if (any(non_zero)) {
    mean(abs((pred[non_zero] - actual[non_zero]) / abs(actual[non_zero])))
  } else { NA}}

mapes <-  all_testis_inter %>%  
            group_by(method, imp) %>%
            summarise(mape_value = abs_mape(prediction, pseudo)) %>%
            mutate(percent = mape_value*100) %>%
            ungroup()

rmse <-  all_testis_inter %>%  
            group_by(method, imp) %>%
            summarise(rmse_value = rmse(prediction, pseudo)) %>%
            ungroup()



mape_minmax <-  all_testis_inter %>% 
 group_by(method, imp, sig_ref) %>%
  summarise(
    mape_value = abs_mape(prediction, pseudo)) %>%
      ungroup()%>%
    group_by(method, imp) %>%
      summarise(
        min=min(mape_value)*100,
        max=max(mape_value)*100)

rmse_minmax <-  all_testis_inter %>% 
 group_by(method, imp, sig_ref) %>%
  summarise(
    rmse_value = rmse(prediction, pseudo)) %>%
      ungroup()%>%
    group_by(method, imp) %>%
      summarise(
        min=min(rmse_value),
        max=max(rmse_value))

testis_inter_mapes_rmse <- list(mapes,mape_minmax,rmse,rmse_minmax)

testis_mapes_rmse <- list("intra" = testis_sames_mapes_rmse, "inter" =testis_inter_mapes_rmse)

saveRDS(testis_mapes_rmse, '~/OneDrive - UW/data for deconv/Paper revision materials/brad_updated_code/testis_mapes_rmse.rds')
```


Load in the testis objects
```{r objects}

testis_results <- readRDS("~/OneDrive - UW/data for deconv/Paper revision materials/brad_updated_code/testis_results.rds")

all_testis_sames <- testis_results$sames %>%
  mutate(imp = if_else(imp == "noIMP", "No Imputation", imp), imp = factor(imp, levels = c("No Imputation", "ALRA", "MAGIC", "SAVER")))

all_testis_inter <- testis_results$inter %>%
  mutate(imp = if_else(imp == "noIMP", "No Imputation", imp), imp = factor(imp, levels = c("No Imputation", "ALRA", "MAGIC", "SAVER")))


```


SAMES plotting - DWLS
```{r plots}



ticks <- c(0.1,0.25,0.50,0.75,0.90)


plots <- ggplot(data=all_testis_sames%>% filter(method== 'dwls'), aes(x=pseudo, y=prediction, color =sig_ref)) +
  geom_point(size=4, shape='diamond', alpha = 0.65) + 
  stat_summary(fun = "mean", geom = "line", size = 1, alpha = 0.8) +  
  geom_abline(slope=1, linetype="dashed") +
  coord_fixed(ratio=1) +  
  scale_x_continuous(breaks=ticks, limits=c(0, 1)) +  
  scale_y_continuous(breaks=ticks, limits=c(0, 1)) +  
  ylab("Predicted Target Cell %") +
  xlab("Actual Target Cell %") +
  scale_color_d3(
    breaks=c('h112', 'h120' ,'h124' , 'md2' , 'md7'),
    labels=c("Adult-H", "Infant-120", "Infant-124", "Day 2-M","Day 7-M")) +    
  theme_minimal(base_size = 20, base_family = "Myriad Pro") +
  theme(legend.position="bottom", axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(color = "Single Cell Reference") +
  guides(color = guide_legend(title.position = "top"))+
  facet_wrap(~imp, nrow=1) 

plots

ggsave(plots, dpi = 600, filename = "~/OneDrive - UW/data for deconv/Paper revision materials/updated_figures/testis_sames/testis-sames_dwls.png", width = 12, height=9, units = 'in', bg = 'white')



```

