---
title: "MUSIC_deconv GUT"
author: "BH"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


We need the RAW count files for MuSIC:

Tutorial here: https://xuranw.github.io/MuSiC/articles/MuSiC.html 

```{r load packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, readxl, ggplot2, ggsci, ggthemes, vroom, readr, tidyverse, DWLS, stringr, Metrics, ggbreak, MuSiC, Seurat, Biobase, SingleCellExperiment)

theme_set(theme_few() + theme(text = element_text(size=28, family="Myriad Pro")))


ctdir <- '~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/Cell refs/'

```


load in the bulk object (this is all merged)

```{r bulk}
bulkpaper1 <- read_delim("~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/Pseudobulks/ALLpseudos_Paper1_NoImp_counts.txt", col_names = T) %>% column_to_rownames("GENEID")

bulkpaper1 <- as.matrix(bulkpaper1)
bulk1 <- apply(bulkpaper1, 2, as.numeric)
colnames(bulk1) <- colnames(bulkpaper1)
rownames(bulk1) <- rownames(bulkpaper1)
colnames(bulk1) <- paste0(colnames(bulk1), "_paper1")



bulkpaper2 <- read_delim("~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/Pseudobulks/ALLpseudos_Paper2_NoImp_counts.txt", col_names = T) %>% column_to_rownames("GENEID")

bulkpaper2 <- as.matrix(bulkpaper2)
bulk2 <- apply(bulkpaper2, 2, as.numeric)
colnames(bulk2) <- colnames(bulkpaper2)
rownames(bulk2) <- rownames(bulkpaper2)
colnames(bulk2) <- paste0(colnames(bulk2), "_paper2")



bulkpaper3 <- read_delim("~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/Pseudobulks/ALLpseudos_Paper3_NoImp_counts.txt", col_names = T) %>% column_to_rownames("GENEID")

bulkpaper3 <- as.matrix(bulkpaper3)
bulk3 <- apply(bulkpaper3, 2, as.numeric)
colnames(bulk3) <- colnames(bulkpaper3)
rownames(bulk3) <- rownames(bulkpaper3)
colnames(bulk3) <- paste0(colnames(bulk3), "_paper3")


bulks <- list(bulk1,bulk2,bulk3)

common_rownames <- Reduce(intersect, lapply(bulks, rownames))

bulks_common <- lapply(bulks, function(df) {df[common_rownames, , drop = FALSE]})

all_bulks <- do.call(cbind, bulks_common)


```


Paper1
```{r paper1 music}

count_matrix <- as.matrix(read_delim(paste0(ctdir,"Paper1_NoImp_CellRef_counts.txt"), col_names = F))

gene_ids <- count_matrix[-1, 1]

cell_types <- as.character(unlist(count_matrix[1, -1]))

count_matrix <- count_matrix[-1, -1]
rownames(count_matrix) <- gene_ids
colnames(count_matrix) <- paste0("cell_", seq_len(ncol(count_matrix)))
numeric_matrix <- apply(count_matrix, 2, as.numeric)

# Assign row and column names back to the matrix
rownames(numeric_matrix) <- rownames(count_matrix)
colnames(numeric_matrix) <- colnames(count_matrix)

cellIDs <- readRDS('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/Labeled seurat objects/paper1_LABELS.rds')
cellIDs$donor <- sub(".*_(.*)", "\\1", cellIDs$cellID)

table(cellIDs$donor)


col_data <- DataFrame(cellIDs)



rownames(col_data) <- colnames(numeric_matrix)

sce <- SingleCellExperiment(assays = list(counts = numeric_matrix), colData = col_data)




paper1_music <- music_prop(all_bulks,sce,clusters = 'clusterID', samples = 'donor')

```
Load in the count objects


Paper2
```{r paper2 music}

count_matrix <- as.matrix(read_delim(paste0(ctdir,"Paper2_NoImp_CellRef_counts.txt"), col_names = F))

gene_ids <- count_matrix[-1, 1]

cell_types <- as.character(unlist(count_matrix[1, -1]))

count_matrix <- count_matrix[-1, -1]
rownames(count_matrix) <- gene_ids
colnames(count_matrix) <- paste0("cell_", seq_len(ncol(count_matrix)))
numeric_matrix <- apply(count_matrix, 2, as.numeric)

# Assign row and column names back to the matrix
rownames(numeric_matrix) <- rownames(count_matrix)
colnames(numeric_matrix) <- colnames(count_matrix)

cellIDs <- readRDS('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/Labeled seurat objects/paper2_LABELS.rds')
cellIDs$donor <- sub(".*_(.*)", "\\1", cellIDs$cellID)

table(cellIDs$donor)


col_data <- DataFrame(cellIDs)



rownames(col_data) <- colnames(numeric_matrix)

sce <- SingleCellExperiment(assays = list(counts = numeric_matrix), colData = col_data)




paper2_music <- music_prop(all_bulks,sce,clusters = 'clusterID', samples = 'donor')

```



Paper3
```{r paper3 music}

count_matrix <- as.matrix(read_delim(paste0(ctdir,"Paper3_NoImp_CellRef_counts.txt"), col_names = F))

gene_ids <- count_matrix[-1, 1]

cell_types <- as.character(unlist(count_matrix[1, -1]))

count_matrix <- count_matrix[-1, -1]
rownames(count_matrix) <- gene_ids
colnames(count_matrix) <- paste0("cell_", seq_len(ncol(count_matrix)))
numeric_matrix <- apply(count_matrix, 2, as.numeric)

# Assign row and column names back to the matrix
rownames(numeric_matrix) <- rownames(count_matrix)
colnames(numeric_matrix) <- colnames(count_matrix)

cellIDs <- readRDS('~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/Labeled seurat objects/paper3_LABELS.rds')
cellIDs$donor <- sub(".*_(.*)", "\\1", cellIDs$cellID)

table(cellIDs$donor)


col_data <- DataFrame(cellIDs)



rownames(col_data) <- colnames(numeric_matrix)

sce <- SingleCellExperiment(assays = list(counts = numeric_matrix), colData = col_data)




paper3_music <- music_prop(all_bulks,sce,clusters = 'clusterID', samples = 'donor')

GUT_music <- list(paper1_music,paper2_music,paper3_music)

saveRDS(GUT_music, '~/OneDrive - UW/data for deconv/Paper revision materials/DATA/raw_counts/GUT/gut_music_results.rds')
```

