---
title: "Reference matrix and pseudobulk creation"
author: "Brad Hansen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, tibble, tidyr, readr, stringr,readxl, ggplot2,ggsci, ggthemes, Seurat, scran, SeuratDisk)

```



LOAD Non-Imputed DATASHEETS USING THE  "combineCPMs_ConvertGenes.Rmd" file

There are 5 datasets:

3 human, 2 mouse

The human objects DO NOT have a "Stroma" cell type. 

The Mouse object DO have a stroma type


Mouse Neonate d2 
```{r m neo d2}
m_neonate_d7 <- SetIdent(m_neonate_d7, value= 'celltype')


a <- tibble(cellID = colnames(m_neonate_d7), clusterID = Idents(m_neonate_d7))

table(a$clusterID)

#   Sertoli     Stroma    Pro-SG/SSC    PTM      Other     diff_SPG     Leydig      Immune     Endo      Lymph 
#     8061       2143       1147       1625       1508        475        349         128        125         40 


#a = object
#b = downsample size
#c = seed set
samp_m <- function(a, b, c){
  
  lg <- subset(a, celltype == "Leydig")
  st <- subset(a, celltype == "Stroma")
  endo <- subset(a, celltype == "Endo")
  ptm <- subset(a, celltype == "PTM")
  d_spg <- subset(a, celltype == "diff_SPG")
  srt <- subset(a, celltype == "Sertoli")
  ssc <- subset(a, celltype == "Pro-SG/SSC")
  imm <- subset(a, celltype == "Immune")
  
  set.seed(c)
  ds_lg <- if(table(Idents(lg)) > b){
            lg[, sample(colnames(lg), size = b, replace = F)]
  } else {
      lg
  }
  set.seed(c)
  ds_d_spg <- if(table(Idents(d_spg)) > b){
            d_spg[, sample(colnames(d_spg), size = b, replace = F)]
  } else {
      d_spg
  }
    set.seed(c)
  ds_st <- if(table(Idents(st)) > b){
            st[, sample(colnames(st), size = b, replace = F)]
  } else {
      st
    }
  set.seed(c)
  ds_ptm <- if(table(Idents(ptm)) > b){
            ptm[, sample(colnames(ptm), size = b, replace = F)]
  } else {
      ptm
    }
  set.seed(c)
  ds_ssc <- if(table(Idents(ssc)) > b){
            ssc[, sample(colnames(ssc), size = b, replace = F)]
  } else {
      ssc
    }
  set.seed(c)
  ds_srt <- if(table(Idents(srt)) > b){
            srt[, sample(colnames(srt), size = b, replace = F)]
  } else {
      srt
    }
  merger <- merge(x = ds_lg, y = list( ds_d_spg, ds_st, ds_ptm,ds_ssc,ds_srt), merge.data = T)
  return(merger)
}

df_samp <- samp_m(m_neonate_d7, 150, 23)

samp2 <- function(a, b, c, d){
  ct <- subset(a, idents = d)
  set.seed(c)
  subs <- ct[, sample(colnames(ct), size = b, replace = F)]
  return(subs)
}

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(m_neonate_d7)[!(colnames(m_neonate_d7) %in% colnames(df_samp))]


#cells_for_pseudo_d7_DIFFlabels <- cells_for_pseudo

#saveRDS(cells_for_pseudo_d7_DIFFlabels, "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/cells_for_pseudo_D7_magic_DIFFlabels.rds")

```

M Neonate d7
```{r m neonate d7 pbs}

pseudo <- m_neonate_d7[ , cells_for_pseudo]


#1 90% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 900, 23, "Sertoli")@assays$cpm$data)
lg <- data.frame(samp2(pseudo, 20, 23, "Leydig")@assays$cpm$data)
st <- data.frame(samp2(pseudo, 20, 23, "Stroma")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 20, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 20, 23, "Pro-SG/SSC")@assays$cpm$data)
d_spg <- data.frame(samp2(pseudo, 20, 23, "diff_SPG")@assays$cpm$data)


pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/m_neonate_d7_DIFFlabels/m_d7_diff_NoImp_srt90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 750, 23, "Sertoli")@assays$cpm$data)
lg <- data.frame(samp2(pseudo, 50, 23, "Leydig")@assays$cpm$data)
st <- data.frame(samp2(pseudo, 50, 23, "Stroma")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 50, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 50, 23, "Pro-SG/SSC")@assays$cpm$data)
d_spg <- data.frame(samp2(pseudo, 50, 23, "diff_SPG")@assays$cpm$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/m_neonate_d7_DIFFlabels/m_d7_diff_NoImp_srt75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)



#3 50% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 500, 23, "Sertoli")@assays$cpm$data)
lg <- data.frame(samp2(pseudo, 100, 23, "Leydig")@assays$cpm$data)
st <- data.frame(samp2(pseudo, 100, 23, "Stroma")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 100, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 100, 23, "Pro-SG/SSC")@assays$cpm$data)
d_spg <- data.frame(samp2(pseudo, 100, 23, "diff_SPG")@assays$cpm$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/m_neonate_d7_DIFFlabels/m_d7_diff_NoImp_srt50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 25% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 250, 23, "Sertoli")@assays$cpm$data)
lg <- data.frame(samp2(pseudo, 150, 23, "Leydig")@assays$cpm$data)
st <- data.frame(samp2(pseudo, 150, 23, "Stroma")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 150, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 150, 23, "Pro-SG/SSC")@assays$cpm$data)
d_spg <- data.frame(samp2(pseudo, 150, 23, "diff_SPG")@assays$cpm$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/m_neonate_d7_DIFFlabels/m_d7_diff_NoImp_srt25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 25% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 100, 23, "Sertoli")@assays$cpm$data)
lg <- data.frame(samp2(pseudo, 180, 23, "Leydig")@assays$cpm$data)
st <- data.frame(samp2(pseudo, 180, 23, "Stroma")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 180, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 180, 23, "Pro-SG/SSC")@assays$cpm$data)
d_spg <- data.frame(samp2(pseudo, 180, 23, "diff_SPG")@assays$cpm$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/m_neonate_d7_DIFFlabels/m_d7_diff_NoImp_srt10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(df_samp, assay = "cpm"))
b$genes <- rownames(b)
#sum(duplicated(b$genes))


# Keep only the Gene Names
mouse_to_rat <-  readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Mouse.rds")

mouse_to_rat <- mouse_to_rat[,c("Mouse_GRCm39_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(mouse_to_rat) <- c("mouse","rat")
mouse_to_rat <- mouse_to_rat %>% distinct() 
mouse_to_rat <- mouse_to_rat %>%
  add_count(rat) %>%           # Add count of occurrences for 'rat'
  filter(n == 1) %>%           # Keep only rows where the 'rat' count is 1 (no duplicates)
  select(-n) 

b <- left_join(b,mouse_to_rat, by = c('genes' = 'mouse')) %>% group_by(rat) %>%
  filter(n() == 1) %>%  ungroup() %>% column_to_rownames(., var="rat") %>% select(-genes)


names(b) <- gsub("\\.", "-", names(b))


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/m_d7_DIFFlabels_noIMP.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```

M neonate d7
```{r m neonate d7 ALRA}

m_d7_ALRA <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/alra/m_neonate_d7_t_alra.rds")


m_d7_ALRA <- m_d7_ALRA[[3]]

m_d7_ALRA <- t(m_d7_ALRA)
colnames(m_d7_ALRA) <- colnames(m_neonate_d7)

ALRA_pseudo <- m_d7_ALRA[,cells_for_pseudo]

pseudo[["ALRA"]] <- CreateAssayObject(data = ALRA_pseudo)


#1 90% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 900, 23, "Sertoli")@assays$ALRA$data)
lg <- data.frame(samp2(pseudo, 20, 23, "Leydig")@assays$ALRA$data)
st <- data.frame(samp2(pseudo, 20, 23, "Stroma")@assays$ALRA$data)
ptm <- data.frame(samp2(pseudo, 20, 23, "PTM")@assays$ALRA$data)
ssc <- data.frame(samp2(pseudo, 20, 23, "Pro-SG/SSC")@assays$ALRA$data)
d_spg <- data.frame(samp2(pseudo, 20, 23, "diff_SPG")@assays$ALRA$data)


pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/m_neonate_d7_DIFFlabels/m_d7_diff_ALRA_srt90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 750, 23, "Sertoli")@assays$ALRA$data)
lg <- data.frame(samp2(pseudo, 50, 23, "Leydig")@assays$ALRA$data)
st <- data.frame(samp2(pseudo, 50, 23, "Stroma")@assays$ALRA$data)
ptm <- data.frame(samp2(pseudo, 50, 23, "PTM")@assays$ALRA$data)
ssc <- data.frame(samp2(pseudo, 50, 23, "Pro-SG/SSC")@assays$ALRA$data)
d_spg <- data.frame(samp2(pseudo, 50, 23, "diff_SPG")@assays$ALRA$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/m_neonate_d7_DIFFlabels/m_d7_diff_ALRA_srt75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)



#3 50% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 500, 23, "Sertoli")@assays$ALRA$data)
lg <- data.frame(samp2(pseudo, 100, 23, "Leydig")@assays$ALRA$data)
st <- data.frame(samp2(pseudo, 100, 23, "Stroma")@assays$ALRA$data)
ptm <- data.frame(samp2(pseudo, 100, 23, "PTM")@assays$ALRA$data)
ssc <- data.frame(samp2(pseudo, 100, 23, "Pro-SG/SSC")@assays$ALRA$data)
d_spg <- data.frame(samp2(pseudo, 100, 23, "diff_SPG")@assays$ALRA$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/m_neonate_d7_DIFFlabels/m_d7_diff_ALRA_srt50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 25% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 250, 23, "Sertoli")@assays$ALRA$data)
lg <- data.frame(samp2(pseudo, 150, 23, "Leydig")@assays$ALRA$data)
st <- data.frame(samp2(pseudo, 150, 23, "Stroma")@assays$ALRA$data)
ptm <- data.frame(samp2(pseudo, 150, 23, "PTM")@assays$ALRA$data)
ssc <- data.frame(samp2(pseudo, 150, 23, "Pro-SG/SSC")@assays$ALRA$data)
d_spg <- data.frame(samp2(pseudo, 150, 23, "diff_SPG")@assays$ALRA$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/m_neonate_d7_DIFFlabels/m_d7_diff_ALRA_srt25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 25% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 100, 23, "Sertoli")@assays$ALRA$data)
lg <- data.frame(samp2(pseudo, 180, 23, "Leydig")@assays$ALRA$data)
st <- data.frame(samp2(pseudo, 180, 23, "Stroma")@assays$ALRA$data)
ptm <- data.frame(samp2(pseudo, 180, 23, "PTM")@assays$ALRA$data)
ssc <- data.frame(samp2(pseudo, 180, 23, "Pro-SG/SSC")@assays$ALRA$data)
d_spg <- data.frame(samp2(pseudo, 180, 23, "diff_SPG")@assays$ALRA$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/m_neonate_d7_DIFFlabels/m_d7_diff_ALRA_srt10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)
### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))

ALRA_samp<- m_d7_ALRA[,colnames(df_samp)]

##
df_samp[["ALRA"]] <- CreateAssayObject(data = ALRA_samp)

b <- data.frame(GetAssayData(df_samp, assay = "ALRA"))
b$genes <- rownames(b)


# Keep only the Gene Names
mouse_to_rat <-  readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Mouse.rds")

mouse_to_rat <- mouse_to_rat[,c("Mouse_GRCm39_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(mouse_to_rat) <- c("mouse","rat")
mouse_to_rat <- mouse_to_rat %>% distinct() 
mouse_to_rat <- mouse_to_rat %>%
  add_count(rat) %>%           # Add count of occurrences for 'rat'
  filter(n == 1) %>%           # Keep only rows where the 'rat' count is 1 (no duplicates)
  select(-n) 

b <- left_join(b,mouse_to_rat, by = c('genes' = 'mouse')) %>% group_by(rat) %>%
  filter(n() == 1) %>%  ungroup() %>% column_to_rownames(., var="rat") %>% select(-genes)


names(b) <- gsub("\\.", "-", names(b))


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/m_d7_DIFF_ALRA.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```


Neonate d7 SAVER
```{r m neonate d7 SAVER}

mnd7_svr <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/saver/md7_saver_cpm_SAVERoutput.rds")


mnd7_svr <- mnd7_svr[[1]]


svr_pseudo <- mnd7_svr[,cells_for_pseudo]
#rm(mnd7_svr)
pseudo <- m_neonate_d7[, cells_for_pseudo]
pseudo[["svr"]] <- CreateAssayObject(data = svr_pseudo)


#1 90% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 900, 23, "Sertoli")@assays$svr$data)
lg <- data.frame(samp2(pseudo, 20, 23, "Leydig")@assays$svr$data)
st <- data.frame(samp2(pseudo, 20, 23, "Stroma")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 20, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 20, 23, "Pro-SG/SSC")@assays$svr$data)
d_spg <- data.frame(samp2(pseudo, 20, 23, "diff_SPG")@assays$svr$data)


pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d7_DIFF/m_d7_diff_SVR_srt90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 750, 23, "Sertoli")@assays$svr$data)
lg <- data.frame(samp2(pseudo, 50, 23, "Leydig")@assays$svr$data)
st <- data.frame(samp2(pseudo, 50, 23, "Stroma")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 50, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 50, 23, "Pro-SG/SSC")@assays$svr$data)
d_spg <- data.frame(samp2(pseudo, 50, 23, "diff_SPG")@assays$svr$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d7_DIFF/m_d7_diff_SVR_srt75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)



#3 50% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 500, 23, "Sertoli")@assays$svr$data)
lg <- data.frame(samp2(pseudo, 100, 23, "Leydig")@assays$svr$data)
st <- data.frame(samp2(pseudo, 100, 23, "Stroma")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 100, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 100, 23, "Pro-SG/SSC")@assays$svr$data)
d_spg <- data.frame(samp2(pseudo, 100, 23, "diff_SPG")@assays$svr$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d7_DIFF/m_d7_diff_SVR_srt50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 25% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 250, 23, "Sertoli")@assays$svr$data)
lg <- data.frame(samp2(pseudo, 150, 23, "Leydig")@assays$svr$data)
st <- data.frame(samp2(pseudo, 150, 23, "Stroma")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 150, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 150, 23, "Pro-SG/SSC")@assays$svr$data)
d_spg <- data.frame(samp2(pseudo, 150, 23, "diff_SPG")@assays$svr$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d7_DIFF/m_d7_diff_SVR_srt25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 25% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 100, 23, "Sertoli")@assays$svr$data)
lg <- data.frame(samp2(pseudo, 180, 23, "Leydig")@assays$svr$data)
st <- data.frame(samp2(pseudo, 180, 23, "Stroma")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 180, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 180, 23, "Pro-SG/SSC")@assays$svr$data)
d_spg <- data.frame(samp2(pseudo, 180, 23, "diff_SPG")@assays$svr$data)

pseudobulk <- cbind(srt,lg, st,ptm,ssc, d_spg) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d7_DIFF/m_d7_diff_SVR_srt10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)
### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
### MAKE CELL REFERENCE

SVR_samp<- mnd7_svr[,colnames(df_samp)]

##
df_samp[["SAVER"]] <- CreateAssayObject(data = SVR_samp)

b <- data.frame(GetAssayData(df_samp, assay = "SAVER"))
b$genes <- rownames(b)




# Keep only the Gene Names
mouse_to_rat <-  readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Mouse.rds")

mouse_to_rat <- mouse_to_rat[,c("Mouse_GRCm39_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(mouse_to_rat) <- c("mouse","rat")
mouse_to_rat <- mouse_to_rat %>% distinct() 
mouse_to_rat <- mouse_to_rat %>%
  add_count(rat) %>%           # Add count of occurrences for 'rat'
  filter(n == 1) %>%           # Keep only rows where the 'rat' count is 1 (no duplicates)
  select(-n) 

b <- left_join(b,mouse_to_rat, by = c('genes' = 'mouse')) %>% group_by(rat) %>%
  filter(n() == 1) %>%  ungroup() %>% column_to_rownames(., var="rat") %>% select(-genes)


names(b) <- gsub("\\.", "-", names(b))


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/m_d7_DIFF_SAVER.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```

```{r m neonate d2 MAGIC}


###options for BRAIN
#magic_hi124 <- fread("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/magic/hi124_MAGIC_matrix.csv")%>% t()


# mgc_pseudo <- data.frame(magic_hi124[,cells_for_pseudo])

#load in the version made on Brain
#mgc_pseudo <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/magic/mgc_pseduo.rds")



#pseudo <- h_infant_124[, cells_for_pseudo]
#pseudo[["magic"]] <- CreateAssayObject(counts = mgc_pseudo)



###

mnd2_mgc <- read_csv("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/magic/mn2_MAGIC_matrix.csv")%>% t()
colnames(mnd2_mgc) <- mnd2_mgc[1,]
mnd2_mgc <- mnd2_mgc[-1,]


mgc_pseudo <- data.frame(mnd2_mgc[,cells_for_pseudo])

pseudo <- m_neonate_d2[, cells_for_pseudo]
pseudo[["mgc"]] <- CreateAssayObject(data = mgc_pseudo)


#1 90% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 900, 23, "Sertoli")@assays$svr$data)
lgSt <- data.frame(samp2(pseudo, 33, 23, "Stroma/Leydig")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 33, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 34, 23, "Pro-SG/SSC")@assays$svr$data)


pseudobulk <- cbind(srt,lgSt,ptm,ssc) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d2/m_neo_d2_SAVER_srt90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 750, 23, "Sertoli")@assays$svr$data)
lgSt <- data.frame(samp2(pseudo, 83, 23, "Stroma/Leydig")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 83, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 84, 23, "Pro-SG/SSC")@assays$svr$data)

pseudobulk <- cbind(srt,lgSt,ptm,ssc) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d2/m_neo_d2_SAVER_srt75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)



#3 50% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 500, 23, "Sertoli")@assays$svr$data)
lgSt <- data.frame(samp2(pseudo, 166, 23, "Stroma/Leydig")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 166, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 168, 23, "Pro-SG/SSC")@assays$svr$data)

pseudobulk <- cbind(srt,lgSt,ptm,ssc) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d2/m_neo_d2_SAVER_srt50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#4 25% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 250, 23, "Sertoli")@assays$svr$data)
lgSt <- data.frame(samp2(pseudo, 250, 23, "Stroma/Leydig")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 250, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 250, 23, "Pro-SG/SSC")@assays$svr$data)

pseudobulk <- cbind(srt,lgSt,ptm,ssc) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d2/m_neo_d2_SAVER_srt25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5 10% Sertoli cells use 1k cells
srt <- data.frame(samp2(pseudo, 100, 23, "Sertoli")@assays$svr$data)
lgSt <- data.frame(samp2(pseudo, 300, 23, "Stroma/Leydig")@assays$svr$data)
ptm <- data.frame(samp2(pseudo, 300, 23, "PTM")@assays$svr$data)
ssc <- data.frame(samp2(pseudo, 300, 23, "Pro-SG/SSC")@assays$svr$data)

pseudobulk <- cbind(srt,lgSt,ptm,ssc) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/m_neonate_d2/m_neo_d2_SAVER_srt10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(df_samp, assay = "cpm"))
b$genes <- rownames(b)
#sum(duplicated(b$genes))


# Keep only the Gene Names
mouse_to_rat <-  readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Mouse.rds")

mouse_to_rat <- mouse_to_rat[,c("Mouse_GRCm39_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(mouse_to_rat) <- c("mouse","rat")
mouse_to_rat <- mouse_to_rat %>% distinct() 
mouse_to_rat <- mouse_to_rat %>%
  add_count(rat) %>%           # Add count of occurrences for 'rat'
  filter(n == 1) %>%           # Keep only rows where the 'rat' count is 1 (no duplicates)
  select(-n) 

b <- left_join(b,mouse_to_rat, by = c('genes' = 'mouse')) %>% group_by(rat) %>%
  filter(n() == 1) %>%  ungroup() %>% column_to_rownames(., var="rat") %>% select(-genes)


names(b) <- gsub("\\.", "-", names(b))


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/m_neo_d2_MAGIC.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```

