---
title: "Reference matrix and pseudobulk creation"
author: "Brad Hansen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr, tibble, tidyr, readr, stringr,readxl, ggplot2,ggsci, ggthemes, Seurat, scran, SeuratDisk)

```



LOAD Non-Imputed DATASHEETS USING THE  "combineCPMs_ConvertGenes.Rmd" file

There are 5 datasets:

3 human, 2 mouse

The human objects DO NOT have a "Stroma" cell type. 

Human Adult 112 
```{r ha112 PsB}

a <- tibble(cellID = colnames(h_adult_112), clusterID = Idents(h_adult_112))

table(a$clusterID)

#a = object
#b = downsample size
#c = seed set
samp_ha <- function(a, b, c){
  
  lg <- subset(a, celltype == "Leydig")
  d_spg <- subset(a, celltype == "d_spg")
  endo <- subset(a, celltype == "Endo")
  ptm <- subset(a, celltype == "PTM")
  ssc <- subset(a, celltype == "SSCs")
  srt <- subset(a, celltype == "Sertoli")
  spc <- subset(a, celltype == "meiosis_spcs")
  imm <- subset(a, celltype == "Immune")
  
  set.seed(c)
  ds_lg <- if(table(Idents(lg)) > b){
            lg[, sample(colnames(lg), size = b, replace = F)]
  } else {
      lg
    }
  set.seed(c)
  ds_d_spg <- if(table(Idents(d_spg)) > b){
            d_spg[, sample(colnames(d_spg), size = b, replace = F)]
  } else {
      d_spg
    }
  set.seed(c)
  ds_endo <- if(table(Idents(endo)) > b){
            endo[, sample(colnames(endo), size = b, replace = F)]
  } else {
      endo
    }
  set.seed(c)
  ds_ptm <- if(table(Idents(ptm)) > b){
            ptm[, sample(colnames(ptm), size = b, replace = F)]
  } else {
      ptm
    }
  set.seed(c)
  ds_ssc <- if(table(Idents(ssc)) > b){
            ssc[, sample(colnames(ssc), size = b, replace = F)]
  } else {
      ssc
    }
  set.seed(c)
  ds_srt <- if(table(Idents(srt)) > b){
            srt[, sample(colnames(srt), size = b, replace = F)]
  } else {
      srt
    }
  set.seed(c)
  ds_spc <- if(table(Idents(spc)) > b){
            spc[, sample(colnames(spc), size = b, replace = F)]
  } else {
      spc
    }
  set.seed(c)
  ds_imm <- if(table(Idents(imm)) > b){
            imm[, sample(colnames(imm), size = b, replace = F)]
  } else {
      imm
    }
  
  merger <- merge(x = ds_lg, y = list(ds_d_spg, ds_endo, ds_ptm, ds_ssc, ds_srt, ds_spc, ds_imm), merge.data = T)
  return(merger)
}

df_samp <- samp_ha(h_adult_112, 150, 23)

samp2 <- function(a, b, c, d){
  ct <- subset(a, idents = d)
  set.seed(c)
  subs <- ct[, sample(colnames(ct), size = b, replace = F)]
  return(subs)
}

#removing the sampled cells to make pseudobulk from the remainder
cells_for_pseudo <- colnames(h_adult_112)[!(colnames(h_adult_112) %in% colnames(df_samp))]
# re-add the Sertoli cells
sertoli_cells <- colnames(subset(h_adult_112, celltype =="Sertoli"))
cells_for_pseudo <- union(cells_for_pseudo, sertoli_cells)





```

Adult Human NoIMP Psuedobulks + Ref
```{r adult 112 pbs}

#table(pseudo$celltype)

#      Leydig      cnd_spm        d_spg        spmtd         Endo          PTM         SSCs meiosis_spcs       Immune 
#         479         2404          288          970          202          154          141          559          194 
#     Sertoli 
#          49 


#We will be making 5 pseudobulks total with 500 cells total - refer to code for ground truth values of cell type proportions
pseudo <- h_adult_112[, cells_to_keep]


#1 90% Leydig cells
lg <- data.frame(samp2(pseudo, 450, 23, "Leydig")@assays$cpm$data)
dspg <- data.frame(samp2(pseudo, 10, 23, "d_spg")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 10, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 10, 23, "SSCs")@assays$cpm$data)
spc <- data.frame(samp2(pseudo, 10, 23, "meiosis_spcs")@assays$cpm$data)
srt <- data.frame(samp2(pseudo, 10, 23, "Sertoli")@assays$cpm$data)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/adult_112/adult112_NoImp_lg90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Leydig cells
lg <- data.frame(samp2(pseudo, 375, 23, "Leydig")@assays$cpm$data)
dspg <- data.frame(samp2(pseudo, 25, 23, "d_spg")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 25, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 25, 23, "SSCs")@assays$cpm$data)
spc <- data.frame(samp2(pseudo, 25, 23, "meiosis_spcs")@assays$cpm$data)
srt <- data.frame(samp2(pseudo, 25, 23, "Sertoli")@assays$cpm$data)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/adult_112/adult112_NoImp_lg75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 50% Leydig cells
lg <- data.frame(samp2(pseudo, 250, 23, "Leydig")@assays$cpm$data)
dspg <- data.frame(samp2(pseudo, 50, 23, "d_spg")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 50, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 51, 23, "SSCs")@assays$cpm$data)
spc <- data.frame(samp2(pseudo, 50, 23, "meiosis_spcs")@assays$cpm$data)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$cpm$data)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/adult_112/adult112_NoImp_lg50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 25% Leydig cells
lg <- data.frame(samp2(pseudo, 125, 23, "Leydig")@assays$cpm$data)
dspg <- data.frame(samp2(pseudo, 81, 23, "d_spg")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 81, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 82, 23, "SSCs")@assays$cpm$data)
spc <- data.frame(samp2(pseudo, 82, 23, "meiosis_spcs")@assays$cpm$data)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$cpm$data)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/adult_112/adult112_NoImp_lg25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5 10% Leydig cells
lg <- data.frame(samp2(pseudo, 50, 23, "Leydig")@assays$cpm$data)
dspg <- data.frame(samp2(pseudo, 101, 23, "d_spg")@assays$cpm$data)
ptm <- data.frame(samp2(pseudo, 100, 23, "PTM")@assays$cpm$data)
ssc <- data.frame(samp2(pseudo, 100, 23, "SSCs")@assays$cpm$data)
spc <- data.frame(samp2(pseudo, 100, 23, "meiosis_spcs")@assays$cpm$data)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$cpm$data)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/noImp/adult_112/adult112_NoImp_lg10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(df_samp, assay = "cpm"))
b$genes <- rownames(b)
#sum(duplicated(b$genes))


human_to_rat <- readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Human.rds")
# Keep only the Gene Names
human_to_rat <- human_to_rat[,c("Human_GRCh38_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(human_to_rat) <- c("human","rat")
human_to_rat <- human_to_rat %>% distinct()

b <- left_join(b,human_to_rat, by = c('genes' = 'human')) %>% column_to_rownames(., var="rat") %>% select(-genes)


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/ha_112.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```

Adult Human ALRA Psuedobulks + Ref
```{r adult 112 pbs}

ha112_ALRA <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/alra/h_adult_112_t_alra.rds")


ha112_ALRA <- ha112_ALRA[[3]]

ha112_ALRA <- t(ha112_ALRA)
colnames(ha112_ALRA) <- colnames(h_adult_112)

ALRA_pseudo <- ha112_ALRA[,cells_for_pseudo]

pseudo[["ALRA"]] <- CreateAssayObject(counts = ALRA_pseudo)


#table(pseudo$celltype)

#      Leydig      cnd_spm        d_spg        spmtd         Endo          PTM         SSCs meiosis_spcs       Immune 
#         479         2404          288          970          202          154          141          559          194 
#     Sertoli 
#          49 


#We will be making 5 pseudobulks total with 500 cells total - refer to code for ground truth values of cell type proportions



#1 90% Leydig cells
lg <- data.frame(samp2(pseudo, 450, 23, "Leydig")@assays$ALRA$data)
dspg <- data.frame(samp2(pseudo, 10, 23, "d_spg")@assays$ALRA$counts)
ptm <- data.frame(samp2(pseudo, 10, 23, "PTM")@assays$ALRA$counts)
ssc <- data.frame(samp2(pseudo, 10, 23, "SSCs")@assays$ALRA$counts)
spc <- data.frame(samp2(pseudo, 10, 23, "meiosis_spcs")@assays$ALRA$counts)
srt <- data.frame(samp2(pseudo, 10, 23, "Sertoli")@assays$ALRA$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/adult112_ALRA_lg90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Leydig cells
lg <- data.frame(samp2(pseudo, 375, 23, "Leydig")@assays$ALRA$counts)
dspg <- data.frame(samp2(pseudo, 25, 23, "d_spg")@assays$ALRA$counts)
ptm <- data.frame(samp2(pseudo, 25, 23, "PTM")@assays$ALRA$counts)
ssc <- data.frame(samp2(pseudo, 25, 23, "SSCs")@assays$ALRA$counts)
spc <- data.frame(samp2(pseudo, 25, 23, "meiosis_spcs")@assays$ALRA$counts)
srt <- data.frame(samp2(pseudo, 25, 23, "Sertoli")@assays$ALRA$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/adult112_ALRA_lg75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 50% Leydig cells
lg <- data.frame(samp2(pseudo, 250, 23, "Leydig")@assays$ALRA$counts)
dspg <- data.frame(samp2(pseudo, 50, 23, "d_spg")@assays$ALRA$counts)
ptm <- data.frame(samp2(pseudo, 50, 23, "PTM")@assays$ALRA$counts)
ssc <- data.frame(samp2(pseudo, 51, 23, "SSCs")@assays$ALRA$counts)
spc <- data.frame(samp2(pseudo, 50, 23, "meiosis_spcs")@assays$ALRA$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$ALRA$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/adult112_ALRA_lg50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 25% Leydig cells
lg <- data.frame(samp2(pseudo, 125, 23, "Leydig")@assays$ALRA$counts)
dspg <- data.frame(samp2(pseudo, 81, 23, "d_spg")@assays$ALRA$counts)
ptm <- data.frame(samp2(pseudo, 81, 23, "PTM")@assays$ALRA$counts)
ssc <- data.frame(samp2(pseudo, 82, 23, "SSCs")@assays$ALRA$counts)
spc <- data.frame(samp2(pseudo, 82, 23, "meiosis_spcs")@assays$ALRA$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$ALRA$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/adult112_ALRA_lg25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5 10% Leydig cells
lg <- data.frame(samp2(pseudo, 50, 23, "Leydig")@assays$ALRA$counts)
dspg <- data.frame(samp2(pseudo, 101, 23, "d_spg")@assays$ALRA$counts)
ptm <- data.frame(samp2(pseudo, 100, 23, "PTM")@assays$ALRA$counts)
ssc <- data.frame(samp2(pseudo, 100, 23, "SSCs")@assays$ALRA$counts)
spc <- data.frame(samp2(pseudo, 100, 23, "meiosis_spcs")@assays$ALRA$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$ALRA$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/ALRA/adult112_ALRA_lg10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

### create the df_samp ALRA object

ref_columns <- colnames(df_samp)

ALRA_ref <- ha112_ALRA[,ref_columns]

df_samp[["ALRA"]] <- CreateAssayObject(counts = ALRA_ref)

### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(df_samp, assay = "ALRA"))
b$genes <- rownames(b)
#sum(duplicated(b$genes))


human_to_rat <- readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Human.rds")
# Keep only the Gene Names
human_to_rat <- human_to_rat[,c("Human_GRCh38_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(human_to_rat) <- c("human","rat")
human_to_rat <- human_to_rat %>% distinct()

b <- left_join(b,human_to_rat, by = c('genes' = 'human')) %>% column_to_rownames(., var="rat") %>% select(-genes)


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/ha_112_ALRA.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```

Adult Human SAVER Psuedobulks + Ref
```{r adult 112 pbs}

ha112_svr <- readRDS("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/saver/ha112_saver_cpm_SAVERoutput.rds")


ha112_svr <- ha112_svr[[1]]


svr_pseudo <- ha112_svr[,cells_for_pseudo]

pseudo <- h_adult_112[, cells_to_keep]
pseudo[["svr"]] <- CreateAssayObject(counts = svr_pseudo)


#table(pseudo$celltype)

#      Leydig      cnd_spm        d_spg        spmtd         Endo          PTM         SSCs meiosis_spcs       Immune 
#         479         2404          288          970          202          154          141          559          194 
#     Sertoli 
#          49 


#We will be making 5 pseudobulks total with 500 cells total - refer to code for ground truth values of cell type proportions



#1 90% Leydig cells
lg <- data.frame(samp2(pseudo, 450, 23, "Leydig")@assays$svr$counts)
dspg <- data.frame(samp2(pseudo, 10, 23, "d_spg")@assays$svr$counts)
ptm <- data.frame(samp2(pseudo, 10, 23, "PTM")@assays$svr$counts)
ssc <- data.frame(samp2(pseudo, 10, 23, "SSCs")@assays$svr$counts)
spc <- data.frame(samp2(pseudo, 10, 23, "meiosis_spcs")@assays$svr$counts)
srt <- data.frame(samp2(pseudo, 10, 23, "Sertoli")@assays$svr$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/adult112_SVR_lg90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Leydig cells
lg <- data.frame(samp2(pseudo, 375, 23, "Leydig")@assays$svr$counts)
dspg <- data.frame(samp2(pseudo, 25, 23, "d_spg")@assays$svr$counts)
ptm <- data.frame(samp2(pseudo, 25, 23, "PTM")@assays$svr$counts)
ssc <- data.frame(samp2(pseudo, 25, 23, "SSCs")@assays$svr$counts)
spc <- data.frame(samp2(pseudo, 25, 23, "meiosis_spcs")@assays$svr$counts)
srt <- data.frame(samp2(pseudo, 25, 23, "Sertoli")@assays$svr$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/adult112_SVR_lg75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 50% Leydig cells
lg <- data.frame(samp2(pseudo, 250, 23, "Leydig")@assays$svr$counts)
dspg <- data.frame(samp2(pseudo, 50, 23, "d_spg")@assays$svr$counts)
ptm <- data.frame(samp2(pseudo, 50, 23, "PTM")@assays$svr$counts)
ssc <- data.frame(samp2(pseudo, 51, 23, "SSCs")@assays$svr$counts)
spc <- data.frame(samp2(pseudo, 50, 23, "meiosis_spcs")@assays$svr$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$svr$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/adult112_SVR_lg50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 25% Leydig cells
lg <- data.frame(samp2(pseudo, 125, 23, "Leydig")@assays$svr$counts)
dspg <- data.frame(samp2(pseudo, 81, 23, "d_spg")@assays$svr$counts)
ptm <- data.frame(samp2(pseudo, 81, 23, "PTM")@assays$svr$counts)
ssc <- data.frame(samp2(pseudo, 82, 23, "SSCs")@assays$svr$counts)
spc <- data.frame(samp2(pseudo, 82, 23, "meiosis_spcs")@assays$svr$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$svr$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/adult112_SVR_lg25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5 10% Leydig cells
lg <- data.frame(samp2(pseudo, 50, 23, "Leydig")@assays$svr$counts)
dspg <- data.frame(samp2(pseudo, 101, 23, "d_spg")@assays$svr$counts)
ptm <- data.frame(samp2(pseudo, 100, 23, "PTM")@assays$svr$counts)
ssc <- data.frame(samp2(pseudo, 100, 23, "SSCs")@assays$svr$counts)
spc <- data.frame(samp2(pseudo, 100, 23, "meiosis_spcs")@assays$svr$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$svr$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/SAVER/adult112_SVR_lg10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

### create the df_samp SAVER object

ref_columns <- colnames(df_samp)

SVRref <- ha112_svr[,ref_columns]

df_samp[["svr"]] <- CreateAssayObject(counts = SVRref)

### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(df_samp, assay = "svr"))
b$genes <- rownames(b)
#sum(duplicated(b$genes))


human_to_rat <- readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Human.rds")
# Keep only the Gene Names
human_to_rat <- human_to_rat[,c("Human_GRCh38_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(human_to_rat) <- c("human","rat")
human_to_rat <- human_to_rat %>% distinct()

b <- left_join(b,human_to_rat, by = c('genes' = 'human')) %>% column_to_rownames(., var="rat") %>% select(-genes)


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/ha_112_SVR.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```


Adult Human MAGIC Psuedobulks + Ref
```{r adult 112 pbs}

## import the NI one for magic as we will add the data later
MGC_h112 <- h_adult_112

magic_h112 <- read_csv("~/OneDrive - UW/data for deconv/Data matrices (C)/Testis/magic/ha112_MAGIC_matrix.csv")%>% t()
colnames(magic_h112) <- magic_h112[1,]
magic_h112 <- magic_h112[-1,]


mgc_pseudo <- data.frame(magic_h112[,cells_for_pseudo])

pseudo <- h_adult_112[, cells_to_keep]
pseudo[["magic"]] <- CreateAssayObject(counts = mgc_pseudo)


#table(pseudo$celltype)

#      Leydig      cnd_spm        d_spg        spmtd         Endo          PTM         SSCs meiosis_spcs       Immune 
#         479         2404          288          970          202          154          141          559          194 
#     Sertoli 
#          49 


#We will be making 5 pseudobulks total with 500 cells total - refer to code for ground truth values of cell type proportions



#1 90% Leydig cells
lg <- data.frame(samp2(pseudo, 450, 23, "Leydig")@assays$magic$counts)
dspg <- data.frame(samp2(pseudo, 10, 23, "d_spg")@assays$magic$counts)
ptm <- data.frame(samp2(pseudo, 10, 23, "PTM")@assays$magic$counts)
ssc <- data.frame(samp2(pseudo, 10, 23, "SSCs")@assays$magic$counts)
spc <- data.frame(samp2(pseudo, 10, 23, "meiosis_spcs")@assays$magic$counts)
srt <- data.frame(samp2(pseudo, 10, 23, "Sertoli")@assays$magic$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"


write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/MAGIC/adult112_magic_lg90.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 75% Leydig cells
lg <- data.frame(samp2(pseudo, 375, 23, "Leydig")@assays$magic$counts)
dspg <- data.frame(samp2(pseudo, 25, 23, "d_spg")@assays$magic$counts)
ptm <- data.frame(samp2(pseudo, 25, 23, "PTM")@assays$magic$counts)
ssc <- data.frame(samp2(pseudo, 25, 23, "SSCs")@assays$magic$counts)
spc <- data.frame(samp2(pseudo, 25, 23, "meiosis_spcs")@assays$magic$counts)
srt <- data.frame(samp2(pseudo, 25, 23, "Sertoli")@assays$magic$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/MAGIC/adult112_magic_lg75.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 50% Leydig cells
lg <- data.frame(samp2(pseudo, 250, 23, "Leydig")@assays$magic$counts)
dspg <- data.frame(samp2(pseudo, 50, 23, "d_spg")@assays$magic$counts)
ptm <- data.frame(samp2(pseudo, 50, 23, "PTM")@assays$magic$counts)
ssc <- data.frame(samp2(pseudo, 51, 23, "SSCs")@assays$magic$counts)
spc <- data.frame(samp2(pseudo, 50, 23, "meiosis_spcs")@assays$magic$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$magic$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"



write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/MAGIC/adult112_magic_lg50.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#2 25% Leydig cells
lg <- data.frame(samp2(pseudo, 125, 23, "Leydig")@assays$magic$counts)
dspg <- data.frame(samp2(pseudo, 81, 23, "d_spg")@assays$magic$counts)
ptm <- data.frame(samp2(pseudo, 81, 23, "PTM")@assays$magic$counts)
ssc <- data.frame(samp2(pseudo, 82, 23, "SSCs")@assays$magic$counts)
spc <- data.frame(samp2(pseudo, 82, 23, "meiosis_spcs")@assays$magic$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$magic$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file =  "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/MAGIC/adult112_magic_lg25.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)


#5 10% Leydig cells
lg <- data.frame(samp2(pseudo, 50, 23, "Leydig")@assays$magic$counts)
dspg <- data.frame(samp2(pseudo, 101, 23, "d_spg")@assays$magic$counts)
ptm <- data.frame(samp2(pseudo, 100, 23, "PTM")@assays$magic$counts)
ssc <- data.frame(samp2(pseudo, 100, 23, "SSCs")@assays$magic$counts)
spc <- data.frame(samp2(pseudo, 100, 23, "meiosis_spcs")@assays$magic$counts)
srt <- data.frame(samp2(pseudo, 49, 23, "Sertoli")@assays$magic$counts)

pseudobulk <- cbind(lg,dspg,ptm,ssc,spc,srt) %>%
  rowMeans() %>%
  as.data.frame() %>%
  rownames_to_column(var = "GENEID")
colnames(pseudobulk)[colnames(pseudobulk) == "."] <- "avg"

write.table(pseudobulk, file = "~/OneDrive - UW/data for deconv/pseudobulks (E)/Testis/MAGIC/adult112_magic_lg10.txt", sep = "\t", quote=FALSE, row.names = FALSE, col.names = TRUE)

### create the df_samp SAVER object

ref_columns <- colnames(df_samp)

magic_ref <- magic_h112[,ref_columns]

df_samp[["magic"]] <- CreateAssayObject(counts = magic_ref)

### MAKE CELL REFERENCE
a <- tibble(cellID = colnames(df_samp), clusterID = Idents(df_samp))
b <- data.frame(GetAssayData(df_samp, assay = "magic"))
b$genes <- rownames(b)
#sum(duplicated(b$genes))


human_to_rat <- readRDS("~/OneDrive - UW/data for deconv/public data (B)/Testis/Rat_to_Human.rds")
# Keep only the Gene Names
human_to_rat <- human_to_rat[,c("Human_GRCh38_GeneSymbol","Rat_mRatBN7.2_GeneSymbol")]
colnames(human_to_rat) <- c("human","rat")
human_to_rat <- human_to_rat %>% distinct()

b <- left_join(b,human_to_rat, by = c('genes' = 'human')) %>% column_to_rownames(., var="rat") %>% select(-genes)


t_a <- data.frame(t(a))
colnames(t_a) <- t_a[1,]

cell_ref <- rbind(t_a, b)
table(colnames(cell_ref) == cell_ref["cellID",])

cell_ref$GENEID <- rownames(cell_ref)
cell_ref <- cell_ref %>%
  relocate(GENEID)

#Getting rid of the cellID row so the cluster ID is now at the top
cell_ref <- cell_ref[-1,]

write.table(cell_ref, 
            file = "~/OneDrive - UW/data for deconv/Testis_cellRefs/ha_112_MAGIC.txt", 
            sep = "\t", quote=FALSE, row.names = FALSE, col.names = F)

```

